//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Catalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Catalog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Catalog", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string btn_ConfirmNO {
            get {
                return ResourceManager.GetString("btn_ConfirmNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string btn_ConfirmYES {
            get {
                return ResourceManager.GetString("btn_ConfirmYES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit catalog.
        /// </summary>
        internal static string btn_EditCatalog {
            get {
                return ResourceManager.GetString("btn_EditCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Params.
        /// </summary>
        internal static string btn_edit_Params {
            get {
                return ResourceManager.GetString("btn_edit_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string gvH_Culture {
            get {
                return ResourceManager.GetString("gvH_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string gvH_CultureID {
            get {
                return ResourceManager.GetString("gvH_CultureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string gvH_Description {
            get {
                return ResourceManager.GetString("gvH_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string gvH_ID {
            get {
                return ResourceManager.GetString("gvH_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 1.
        /// </summary>
        internal static string gvH_Param1 {
            get {
                return ResourceManager.GetString("gvH_Param1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 2.
        /// </summary>
        internal static string gvH_Param2 {
            get {
                return ResourceManager.GetString("gvH_Param2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 3.
        /// </summary>
        internal static string gvH_Param3 {
            get {
                return ResourceManager.GetString("gvH_Param3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 4.
        /// </summary>
        internal static string gvH_Param4 {
            get {
                return ResourceManager.GetString("gvH_Param4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value ID.
        /// </summary>
        internal static string gvH_ValueID {
            get {
                return ResourceManager.GetString("gvH_ValueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string lbl_Catalog {
            get {
                return ResourceManager.GetString("lbl_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lbl_CatalogDescription {
            get {
                return ResourceManager.GetString("lbl_CatalogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_CatalogName {
            get {
                return ResourceManager.GetString("lbl_CatalogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string lbl_CatalogTag {
            get {
                return ResourceManager.GetString("lbl_CatalogTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured.
        /// </summary>
        internal static string lbl_Configure {
            get {
                return ResourceManager.GetString("lbl_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string lbl_Culture {
            get {
                return ResourceManager.GetString("lbl_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        internal static string lbl_Delete {
            get {
                return ResourceManager.GetString("lbl_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lbl_Description {
            get {
                return ResourceManager.GetString("lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        internal static string lbl_Facility {
            get {
                return ResourceManager.GetString("lbl_Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is system value.
        /// </summary>
        internal static string lbl_IsSystemValue {
            get {
                return ResourceManager.GetString("lbl_IsSystemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New City.
        /// </summary>
        internal static string lbl_NewCity {
            get {
                return ResourceManager.GetString("lbl_NewCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New State.
        /// </summary>
        internal static string lbl_NewState {
            get {
                return ResourceManager.GetString("lbl_NewState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string lbl_Organization {
            get {
                return ResourceManager.GetString("lbl_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 1.
        /// </summary>
        internal static string lbl_Param1 {
            get {
                return ResourceManager.GetString("lbl_Param1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 2.
        /// </summary>
        internal static string lbl_Param2 {
            get {
                return ResourceManager.GetString("lbl_Param2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 3.
        /// </summary>
        internal static string lbl_Param3 {
            get {
                return ResourceManager.GetString("lbl_Param3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param 4.
        /// </summary>
        internal static string lbl_Param4 {
            get {
                return ResourceManager.GetString("lbl_Param4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lbl_ParamDescription {
            get {
                return ResourceManager.GetString("lbl_ParamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_ParamName {
            get {
                return ResourceManager.GetString("lbl_ParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lbl_ParamNumber {
            get {
                return ResourceManager.GetString("lbl_ParamNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value ID.
        /// </summary>
        internal static string lbl_ValueID {
            get {
                return ResourceManager.GetString("lbl_ValueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing catalog name.
        /// </summary>
        internal static string MissingCatalogName {
            get {
                return ResourceManager.GetString("MissingCatalogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing catalog tag.
        /// </summary>
        internal static string MissingCatalogTag {
            get {
                return ResourceManager.GetString("MissingCatalogTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing description.
        /// </summary>
        internal static string MissingDescription {
            get {
                return ResourceManager.GetString("MissingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing facility.
        /// </summary>
        internal static string MissingFacility {
            get {
                return ResourceManager.GetString("MissingFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing organization.
        /// </summary>
        internal static string MissingOrganization {
            get {
                return ResourceManager.GetString("MissingOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing valueID.
        /// </summary>
        internal static string MissingValueID {
            get {
                return ResourceManager.GetString("MissingValueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a vendor please.
        /// </summary>
        internal static string ntf_SelectVendor {
            get {
                return ResourceManager.GetString("ntf_SelectVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a warehouse please.
        /// </summary>
        internal static string ntf_SelectWarehouse {
            get {
                return ResourceManager.GetString("ntf_SelectWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Params updated .
        /// </summary>
        internal static string ParamsUpdated {
            get {
                return ResourceManager.GetString("ParamsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs.
        /// </summary>
        internal static string title_Catalog {
            get {
                return ResourceManager.GetString("title_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure parameters.
        /// </summary>
        internal static string title_ConfigureParameters {
            get {
                return ResourceManager.GetString("title_ConfigureParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete?.
        /// </summary>
        internal static string title_ConfirmDelete {
            get {
                return ResourceManager.GetString("title_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new catalog.
        /// </summary>
        internal static string title_CreateCatalog {
            get {
                return ResourceManager.GetString("title_CreateCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string title_Details {
            get {
                return ResourceManager.GetString("title_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit catalog.
        /// </summary>
        internal static string title_EditCatalog {
            get {
                return ResourceManager.GetString("title_EditCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Translations for Value ID.
        /// </summary>
        internal static string title_EditTraslations {
            get {
                return ResourceManager.GetString("title_EditTraslations", resourceCulture);
            }
        }
    }
}
