//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.CI {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CI.Dashboard", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard All Reports.
        /// </summary>
        internal static string lbl_DashboardGasket_AllDashboardReports {
            get {
                return ResourceManager.GetString("lbl_DashboardGasket_AllDashboardReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downtimes Report (In Minutes).
        /// </summary>
        internal static string lbl_DashboardGasket_DowntimesReport {
            get {
                return ResourceManager.GetString("lbl_DashboardGasket_DowntimesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Production Report.
        /// </summary>
        internal static string lbl_DashboardGasket_ProductionReport {
            get {
                return ResourceManager.GetString("lbl_DashboardGasket_ProductionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yield Defects Report.
        /// </summary>
        internal static string lbl_DashboardGasket_YieldDefectsReport {
            get {
                return ResourceManager.GetString("lbl_DashboardGasket_YieldDefectsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export All Reports.
        /// </summary>
        internal static string lbl_ExportAllReports {
            get {
                return ResourceManager.GetString("lbl_ExportAllReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visits.
        /// </summary>
        internal static string lbl_Visits {
            get {
                return ResourceManager.GetString("lbl_Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información se exportará con los siguientes filtros..
        /// </summary>
        internal static string msg_FiltersForReport {
            get {
                return ResourceManager.GetString("msg_FiltersForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuous Improvement.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove filter.
        /// </summary>
        internal static string tt_RemoveFilter {
            get {
                return ResourceManager.GetString("tt_RemoveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to Dashboard!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
