//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.CI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DashboardManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CI.DashboardManagement", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Section.
        /// </summary>
        internal static string btnCreateSectionTag {
            get {
                return ResourceManager.GetString("btnCreateSectionTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Details.
        /// </summary>
        internal static string btn_SectionDetailsTag {
            get {
                return ResourceManager.GetString("btn_SectionDetailsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Detail.
        /// </summary>
        internal static string btn_UpdateSectionDetailsTag {
            get {
                return ResourceManager.GetString("btn_UpdateSectionDetailsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string gvh_AreaTag {
            get {
                return ResourceManager.GetString("gvh_AreaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Color.
        /// </summary>
        internal static string gvh_BackColorTag {
            get {
                return ResourceManager.GetString("gvh_BackColorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string gvh_DetailNameTag {
            get {
                return ResourceManager.GetString("gvh_DetailNameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string gvh_DetailSizeTag {
            get {
                return ResourceManager.GetString("gvh_DetailSizeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string gvh_FileTypeTag {
            get {
                return ResourceManager.GetString("gvh_FileTypeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        internal static string gvh_FontColorTag {
            get {
                return ResourceManager.GetString("gvh_FontColorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        internal static string gvh_FooterTag {
            get {
                return ResourceManager.GetString("gvh_FooterTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string gvh_IconTag {
            get {
                return ResourceManager.GetString("gvh_IconTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent node.
        /// </summary>
        internal static string gvh_ParentNode {
            get {
                return ResourceManager.GetString("gvh_ParentNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string gvh_SequenceTag {
            get {
                return ResourceManager.GetString("gvh_SequenceTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string gvh_Settings_File {
            get {
                return ResourceManager.GetString("gvh_Settings_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string gvh_Settings_Seq {
            get {
                return ResourceManager.GetString("gvh_Settings_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string gvh_SizeTag {
            get {
                return ResourceManager.GetString("gvh_SizeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string lbl_AddAreaTag {
            get {
                return ResourceManager.GetString("lbl_AddAreaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string lbl_AreaNameTag {
            get {
                return ResourceManager.GetString("lbl_AreaNameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string lbl_BackColorTag {
            get {
                return ResourceManager.GetString("lbl_BackColorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        internal static string lbl_BackgroundImage {
            get {
                return ResourceManager.GetString("lbl_BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        internal static string lbl_BackgroundImageTag {
            get {
                return ResourceManager.GetString("lbl_BackgroundImageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrusel de Videos.
        /// </summary>
        internal static string lbl_CarouselVideosTag {
            get {
                return ResourceManager.GetString("lbl_CarouselVideosTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close windows detail after.
        /// </summary>
        internal static string lbl_CloseWindowAfterTag {
            get {
                return ResourceManager.GetString("lbl_CloseWindowAfterTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Section.
        /// </summary>
        internal static string lbl_DashboardAreaAddTag {
            get {
                return ResourceManager.GetString("lbl_DashboardAreaAddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Section Details.
        /// </summary>
        internal static string lbl_DashboardAreaDetailHeaderTag {
            get {
                return ResourceManager.GetString("lbl_DashboardAreaDetailHeaderTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Section Details.
        /// </summary>
        internal static string lbl_DashboardAreaDetailHeaderUpdateTag {
            get {
                return ResourceManager.GetString("lbl_DashboardAreaDetailHeaderUpdateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Node.
        /// </summary>
        internal static string lbl_DashboardAreaNodeHeaderTag {
            get {
                return ResourceManager.GetString("lbl_DashboardAreaNodeHeaderTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Node.
        /// </summary>
        internal static string lbl_DashboardAreaNodeHeaderUpdateTag {
            get {
                return ResourceManager.GetString("lbl_DashboardAreaNodeHeaderUpdateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Duration.
        /// </summary>
        internal static string lbl_DataEffectDurationTag {
            get {
                return ResourceManager.GetString("lbl_DataEffectDurationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect.
        /// </summary>
        internal static string lbl_DataEffectTag {
            get {
                return ResourceManager.GetString("lbl_DataEffectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_DetailNameTag {
            get {
                return ResourceManager.GetString("lbl_DetailNameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files to attach, or browse.
        /// </summary>
        internal static string lbl_Dropfiles {
            get {
                return ResourceManager.GetString("lbl_Dropfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - File not valid.
        /// </summary>
        internal static string lbl_FileNotValidTag {
            get {
                return ResourceManager.GetString("lbl_FileNotValidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string lbl_FileTypeTag {
            get {
                return ResourceManager.GetString("lbl_FileTypeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font color.
        /// </summary>
        internal static string lbl_FontColorTag {
            get {
                return ResourceManager.GetString("lbl_FontColorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter footer.
        /// </summary>
        internal static string lbl_FooterPhTag {
            get {
                return ResourceManager.GetString("lbl_FooterPhTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        internal static string lbl_FooterTag {
            get {
                return ResourceManager.GetString("lbl_FooterTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Setting Dashboard.
        /// </summary>
        internal static string lbl_GeneralSettingsTag {
            get {
                return ResourceManager.GetString("lbl_GeneralSettingsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gral Setting.
        /// </summary>
        internal static string lbl_GrlSettingTag {
            get {
                return ResourceManager.GetString("lbl_GrlSettingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string lbl_HrefTag {
            get {
                return ResourceManager.GetString("lbl_HrefTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string lbl_IconTag {
            get {
                return ResourceManager.GetString("lbl_IconTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Management.
        /// </summary>
        internal static string lbl_MainHeader_tag {
            get {
                return ResourceManager.GetString("lbl_MainHeader_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure wish to delete record?.
        /// </summary>
        internal static string lbl_MsgDeleteDashboardAreaDetailTag {
            get {
                return ResourceManager.GetString("lbl_MsgDeleteDashboardAreaDetailTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure wish to delete record and your content ?.
        /// </summary>
        internal static string lbl_MsgDeleteDashboardAreaTag {
            get {
                return ResourceManager.GetString("lbl_MsgDeleteDashboardAreaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to wish delete video?.
        /// </summary>
        internal static string lbl_MsgDeleteFileTag {
            get {
                return ResourceManager.GetString("lbl_MsgDeleteFileTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        internal static string lbl_Node {
            get {
                return ResourceManager.GetString("lbl_Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a single file.
        /// </summary>
        internal static string lbl_OnlyOnceFileTag {
            get {
                return ResourceManager.GetString("lbl_OnlyOnceFileTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent .
        /// </summary>
        internal static string lbl_Parent {
            get {
                return ResourceManager.GetString("lbl_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Saver Interval.
        /// </summary>
        internal static string lbl_ScreenSaverIntervalTag {
            get {
                return ResourceManager.GetString("lbl_ScreenSaverIntervalTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Saver Video.
        /// </summary>
        internal static string lbl_ScreenSaverVideoTag {
            get {
                return ResourceManager.GetString("lbl_ScreenSaverVideoTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string lbl_SecondsTag {
            get {
                return ResourceManager.GetString("lbl_SecondsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string lbl_Section {
            get {
                return ResourceManager.GetString("lbl_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string lbl_SeqTag {
            get {
                return ResourceManager.GetString("lbl_SeqTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string lbl_SizeTag {
            get {
                return ResourceManager.GetString("lbl_SizeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path File.
        /// </summary>
        internal static string lbl_SourcePathTag {
            get {
                return ResourceManager.GetString("lbl_SourcePathTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Video.
        /// </summary>
        internal static string lbl_TitleDeleteFileTag {
            get {
                return ResourceManager.GetString("lbl_TitleDeleteFileTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_TitleNameTag {
            get {
                return ResourceManager.GetString("lbl_TitleNameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lbl_UpdateGralSettingTag {
            get {
                return ResourceManager.GetString("lbl_UpdateGralSettingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to upload image .
        /// </summary>
        internal static string lbl_UploadImageTag {
            get {
                return ResourceManager.GetString("lbl_UploadImageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to upload a video.
        /// </summary>
        internal static string lbl_UploadVideoTag {
            get {
                return ResourceManager.GetString("lbl_UploadVideoTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string lbl_View {
            get {
                return ResourceManager.GetString("lbl_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node belongs to a different section.
        /// </summary>
        internal static string nft_DifferentSectionNode {
            get {
                return ResourceManager.GetString("nft_DifferentSectionNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections cannot be separated.
        /// </summary>
        internal static string ntf_SectionSeparated {
            get {
                return ResourceManager.GetString("ntf_SectionSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add section.
        /// </summary>
        internal static string tt_AddAreaTag {
            get {
                return ResourceManager.GetString("tt_AddAreaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add details.
        /// </summary>
        internal static string tt_AddDashboardAreaDetail {
            get {
                return ResourceManager.GetString("tt_AddDashboardAreaDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new section.
        /// </summary>
        internal static string tt_CreateSectionTag {
            get {
                return ResourceManager.GetString("tt_CreateSectionTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete detail ...
        /// </summary>
        internal static string tt_DeleteDashboardAreaDetailTag {
            get {
                return ResourceManager.GetString("tt_DeleteDashboardAreaDetailTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete section ...
        /// </summary>
        internal static string tt_DeleteDashboardAreaTag {
            get {
                return ResourceManager.GetString("tt_DeleteDashboardAreaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit section ...
        /// </summary>
        internal static string tt_EditDashboardArea {
            get {
                return ResourceManager.GetString("tt_EditDashboardArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Section....
        /// </summary>
        internal static string tt_EditDashboardAreaTag {
            get {
                return ResourceManager.GetString("tt_EditDashboardAreaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit details ...
        /// </summary>
        internal static string tt_EditDashboardDetail {
            get {
                return ResourceManager.GetString("tt_EditDashboardDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string tt_GralSettingTag {
            get {
                return ResourceManager.GetString("tt_GralSettingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Sections.
        /// </summary>
        internal static string tt_ReorderSections {
            get {
                return ResourceManager.GetString("tt_ReorderSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a current video.
        /// </summary>
        internal static string tt_SettingsPlay {
            get {
                return ResourceManager.GetString("tt_SettingsPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string tt_UpdateGralSettingTag {
            get {
                return ResourceManager.GetString("tt_UpdateGralSettingTag", resourceCulture);
            }
        }
    }
}
