//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDeleteTag {
            get {
                return ResourceManager.GetString("btnDeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BtnOK_Messages {
            get {
                return ResourceManager.GetString("BtnOK_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string btn_Accept {
            get {
                return ResourceManager.GetString("btn_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string btn_Approve {
            get {
                return ResourceManager.GetString("btn_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string btn_Back {
            get {
                return ResourceManager.GetString("btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string btn_Clone {
            get {
                return ResourceManager.GetString("btn_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string btn_Confirm {
            get {
                return ResourceManager.GetString("btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string btn_ConfirmNO {
            get {
                return ResourceManager.GetString("btn_ConfirmNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string btn_ConfirmYES {
            get {
                return ResourceManager.GetString("btn_ConfirmYES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string btn_Create {
            get {
                return ResourceManager.GetString("btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string btn_New {
            get {
                return ResourceManager.GetString("btn_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string btn_Next {
            get {
                return ResourceManager.GetString("btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btn_OK {
            get {
                return ResourceManager.GetString("btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string btn_Prev {
            get {
                return ResourceManager.GetString("btn_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string btn_Reject {
            get {
                return ResourceManager.GetString("btn_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string btn_SaveChanges {
            get {
                return ResourceManager.GetString("btn_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btn_Search {
            get {
                return ResourceManager.GetString("btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string btn_Select {
            get {
                return ResourceManager.GetString("btn_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string btn_ShowAll {
            get {
                return ResourceManager.GetString("btn_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btn_Submit {
            get {
                return ResourceManager.GetString("btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btn_UpdateDownTime {
            get {
                return ResourceManager.GetString("btn_UpdateDownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data.
        /// </summary>
        internal static string chsn_NoResults {
            get {
                return ResourceManager.GetString("chsn_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Some Options.
        /// </summary>
        internal static string chsn_SelectMultipleOption {
            get {
                return ResourceManager.GetString("chsn_SelectMultipleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option.
        /// </summary>
        internal static string chsn_SelectOption {
            get {
                return ResourceManager.GetString("chsn_SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing page _PAGE_ of _PAGES_.
        /// </summary>
        internal static string dtatbl_info {
            get {
                return ResourceManager.GetString("dtatbl_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display _MENU_ records per page.
        /// </summary>
        internal static string dtatbl_LengthMenu {
            get {
                return ResourceManager.GetString("dtatbl_LengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        internal static string dtatbl_sEmptyTable {
            get {
                return ResourceManager.GetString("dtatbl_sEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string dtatbl_sFirst {
            get {
                return ResourceManager.GetString("dtatbl_sFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        internal static string dtatbl_sInfoEmpty {
            get {
                return ResourceManager.GetString("dtatbl_sInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total entries).
        /// </summary>
        internal static string dtatbl_sInfoFiltered {
            get {
                return ResourceManager.GetString("dtatbl_sInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string dtatbl_sLast {
            get {
                return ResourceManager.GetString("dtatbl_sLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string dtatbl_sLoadingRecords {
            get {
                return ResourceManager.GetString("dtatbl_sLoadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string dtatbl_sNext {
            get {
                return ResourceManager.GetString("dtatbl_sNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string dtatbl_sPrevious {
            get {
                return ResourceManager.GetString("dtatbl_sPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string dtatbl_sProcessing {
            get {
                return ResourceManager.GetString("dtatbl_sProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string dtatbl_sSearch {
            get {
                return ResourceManager.GetString("dtatbl_sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : activate to sort column ascending.
        /// </summary>
        internal static string dtatbl_sSortAsc {
            get {
                return ResourceManager.GetString("dtatbl_sSortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : activate to sort column descending.
        /// </summary>
        internal static string dtatbl_sSortDesc {
            get {
                return ResourceManager.GetString("dtatbl_sSortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        internal static string dtatbl_sZeroRecords {
            get {
                return ResourceManager.GetString("dtatbl_sZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        internal static string gvH_DateAdded {
            get {
                return ResourceManager.GetString("gvH_DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated on.
        /// </summary>
        internal static string gvH_DateLastMaint {
            get {
                return ResourceManager.GetString("gvH_DateLastMaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string gvH_Enabled {
            get {
                return ResourceManager.GetString("gvH_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string gvH_File {
            get {
                return ResourceManager.GetString("gvH_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string gvH_Options {
            get {
                return ResourceManager.GetString("gvH_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string gvH_Print {
            get {
                return ResourceManager.GetString("gvH_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string gvH_RowNumber {
            get {
                return ResourceManager.GetString("gvH_RowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string gvH_Select {
            get {
                return ResourceManager.GetString("gvH_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated by.
        /// </summary>
        internal static string gvH_UpdatedBy {
            get {
                return ResourceManager.GetString("gvH_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated on.
        /// </summary>
        internal static string gvH_UpdatedOn {
            get {
                return ResourceManager.GetString("gvH_UpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string gvH_UserName {
            get {
                return ResourceManager.GetString("gvH_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        internal static string lbl_Access {
            get {
                return ResourceManager.GetString("lbl_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files to attach, or browse.
        /// </summary>
        internal static string lbl_AttachFiles {
            get {
                return ResourceManager.GetString("lbl_AttachFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        internal static string lbl_BuildBy {
            get {
                return ResourceManager.GetString("lbl_BuildBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string lbl_By {
            get {
                return ResourceManager.GetString("lbl_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lbl_Cancel {
            get {
                return ResourceManager.GetString("lbl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change facility.
        /// </summary>
        internal static string lbl_ChangeFacility {
            get {
                return ResourceManager.GetString("lbl_ChangeFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string lbl_ChangeLanguage {
            get {
                return ResourceManager.GetString("lbl_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Request.
        /// </summary>
        internal static string lbl_ChangeRequest {
            get {
                return ResourceManager.GetString("lbl_ChangeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string lbl_Clear {
            get {
                return ResourceManager.GetString("lbl_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string lbl_Continue {
            get {
                return ResourceManager.GetString("lbl_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy As.
        /// </summary>
        internal static string lbl_CopyAs {
            get {
                return ResourceManager.GetString("lbl_CopyAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string lbl_Create {
            get {
                return ResourceManager.GetString("lbl_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string lbl_Createdby {
            get {
                return ResourceManager.GetString("lbl_Createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        internal static string lbl_CreatedOn {
            get {
                return ResourceManager.GetString("lbl_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string lbl_Culture {
            get {
                return ResourceManager.GetString("lbl_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string lbl_CurrentPage {
            get {
                return ResourceManager.GetString("lbl_CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lbl_Date {
            get {
                return ResourceManager.GetString("lbl_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date type Filter.
        /// </summary>
        internal static string lbl_DatetypeFilter {
            get {
                return ResourceManager.GetString("lbl_DatetypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        internal static string lbl_Del {
            get {
                return ResourceManager.GetString("lbl_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lbl_Delete {
            get {
                return ResourceManager.GetString("lbl_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string lbl_Department {
            get {
                return ResourceManager.GetString("lbl_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lbl_Description {
            get {
                return ResourceManager.GetString("lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string lbl_Detail {
            get {
                return ResourceManager.GetString("lbl_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string lbl_Disable {
            get {
                return ResourceManager.GetString("lbl_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string lbl_Disabled {
            get {
                return ResourceManager.GetString("lbl_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string lbl_DocumentType {
            get {
                return ResourceManager.GetString("lbl_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string lbl_Domain {
            get {
                return ResourceManager.GetString("lbl_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files to attach, or browse.
        /// </summary>
        internal static string lbl_Dropfiles {
            get {
                return ResourceManager.GetString("lbl_Dropfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to take a photo of the identification.
        /// </summary>
        internal static string lbl_DropzoneClickToTake {
            get {
                return ResourceManager.GetString("lbl_DropzoneClickToTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string lbl_Edit {
            get {
                return ResourceManager.GetString("lbl_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string lbl_Enable {
            get {
                return ResourceManager.GetString("lbl_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string lbl_Enabled {
            get {
                return ResourceManager.GetString("lbl_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string lbl_EndDate {
            get {
                return ResourceManager.GetString("lbl_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lbl_English {
            get {
                return ResourceManager.GetString("lbl_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we&apos;re sorry....
        /// </summary>
        internal static string lbl_ErrorMessage {
            get {
                return ResourceManager.GetString("lbl_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred on our website. The website administrator has been notified..
        /// </summary>
        internal static string lbl_ErrorMessage2 {
            get {
                return ResourceManager.GetString("lbl_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string lbl_Exit {
            get {
                return ResourceManager.GetString("lbl_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        internal static string lbl_Facility {
            get {
                return ResourceManager.GetString("lbl_Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string lbl_False {
            get {
                return ResourceManager.GetString("lbl_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string lbl_FileName {
            get {
                return ResourceManager.GetString("lbl_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        internal static string lbl_FileType {
            get {
                return ResourceManager.GetString("lbl_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by date.
        /// </summary>
        internal static string lbl_Filterbydate {
            get {
                return ResourceManager.GetString("lbl_Filterbydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string lbl_Filters {
            get {
                return ResourceManager.GetString("lbl_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string lbl_Help {
            get {
                return ResourceManager.GetString("lbl_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid access to this option.
        /// </summary>
        internal static string lbl_InvalidAccess {
            get {
                return ResourceManager.GetString("lbl_InvalidAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lbl_language {
            get {
                return ResourceManager.GetString("lbl_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string lbl_Loading {
            get {
                return ResourceManager.GetString("lbl_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus.
        /// </summary>
        internal static string lbl_Menus {
            get {
                return ResourceManager.GetString("lbl_Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string lbl_Message {
            get {
                return ResourceManager.GetString("lbl_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified by.
        /// </summary>
        internal static string lbl_Modifiedby {
            get {
                return ResourceManager.GetString("lbl_Modifiedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lbl_NO {
            get {
                return ResourceManager.GetString("lbl_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string lbl_OK {
            get {
                return ResourceManager.GetString("lbl_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string lbl_On {
            get {
                return ResourceManager.GetString("lbl_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string lbl_Options {
            get {
                return ResourceManager.GetString("lbl_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lbl_Password {
            get {
                return ResourceManager.GetString("lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string lbl_Print {
            get {
                return ResourceManager.GetString("lbl_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print report.
        /// </summary>
        internal static string lbl_PrintReport {
            get {
                return ResourceManager.GetString("lbl_PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing ....
        /// </summary>
        internal static string lbl_Processing {
            get {
                return ResourceManager.GetString("lbl_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string lbl_Refresh {
            get {
                return ResourceManager.GetString("lbl_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re print.
        /// </summary>
        internal static string lbl_Reprint {
            get {
                return ResourceManager.GetString("lbl_Reprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string lbl_Reset {
            get {
                return ResourceManager.GetString("lbl_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string lbl_Search {
            get {
                return ResourceManager.GetString("lbl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by All.
        /// </summary>
        internal static string lbl_SearchByAll {
            get {
                return ResourceManager.GetString("lbl_SearchByAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string lbl_Seq {
            get {
                return ResourceManager.GetString("lbl_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string lbl_Spanish {
            get {
                return ResourceManager.GetString("lbl_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string lbl_StartDate {
            get {
                return ResourceManager.GetString("lbl_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lbl_Status {
            get {
                return ResourceManager.GetString("lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lbl_Title {
            get {
                return ResourceManager.GetString("lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string lbl_To {
            get {
                return ResourceManager.GetString("lbl_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string lbl_TotalRecords {
            get {
                return ResourceManager.GetString("lbl_TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string lbl_True {
            get {
                return ResourceManager.GetString("lbl_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string lbl_Update {
            get {
                return ResourceManager.GetString("lbl_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated by.
        /// </summary>
        internal static string lbl_Updatedby {
            get {
                return ResourceManager.GetString("lbl_Updatedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lbl_User {
            get {
                return ResourceManager.GetString("lbl_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User and password.
        /// </summary>
        internal static string lbl_UserAndPassword {
            get {
                return ResourceManager.GetString("lbl_UserAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string lbl_View {
            get {
                return ResourceManager.GetString("lbl_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View attachments.
        /// </summary>
        internal static string lbl_ViewAttachments {
            get {
                return ResourceManager.GetString("lbl_ViewAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        internal static string lbl_ViewDetails {
            get {
                return ResourceManager.GetString("lbl_ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string lbl_Warning {
            get {
                return ResourceManager.GetString("lbl_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string lbl_Week {
            get {
                return ResourceManager.GetString("lbl_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string lbl_Year {
            get {
                return ResourceManager.GetString("lbl_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string lbl_Yes {
            get {
                return ResourceManager.GetString("lbl_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist, please verify.
        /// </summary>
        internal static string nft_FileNotExists {
            get {
                return ResourceManager.GetString("nft_FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been loaded succesfully.
        /// </summary>
        internal static string nft_FileUploaded {
            get {
                return ResourceManager.GetString("nft_FileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None selected.
        /// </summary>
        internal static string noneSelected {
            get {
                return ResourceManager.GetString("noneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this attachment file?.
        /// </summary>
        internal static string ntf_DeleteAttachment {
            get {
                return ResourceManager.GetString("ntf_DeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string ntf_DeleteItem {
            get {
                return ResourceManager.GetString("ntf_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Session.
        /// </summary>
        internal static string ntf_ExpiredSession {
            get {
                return ResourceManager.GetString("ntf_ExpiredSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        internal static string ntf_InValidUser {
            get {
                return ResourceManager.GetString("ntf_InValidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not file.
        /// </summary>
        internal static string ntf_Nofile {
            get {
                return ResourceManager.GetString("ntf_Nofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown template report.
        /// </summary>
        internal static string ntf_UnknowTemplate {
            get {
                return ResourceManager.GetString("ntf_UnknowTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid user.
        /// </summary>
        internal static string ntf_ValidUser {
            get {
                return ResourceManager.GetString("ntf_ValidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select options.
        /// </summary>
        internal static string placeholder {
            get {
                return ResourceManager.GetString("placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string selectAll {
            get {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string selectedOptions {
            get {
                return ResourceManager.GetString("selectedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        internal static string TagAll {
            get {
                return ResourceManager.GetString("TagAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to CEMA.
        /// </summary>
        internal static string tilte_login {
            get {
                return ResourceManager.GetString("tilte_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this item?.
        /// </summary>
        internal static string title_ConfirmDelete {
            get {
                return ResourceManager.GetString("title_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string title_Error {
            get {
                return ResourceManager.GetString("title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string title_Login {
            get {
                return ResourceManager.GetString("title_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        internal static string title_Resource {
            get {
                return ResourceManager.GetString("title_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFI.
        /// </summary>
        internal static string title_Sofi {
            get {
                return ResourceManager.GetString("title_Sofi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special access required.
        /// </summary>
        internal static string title_SpecialAccess {
            get {
                return ResourceManager.GetString("title_SpecialAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string title_Success {
            get {
                return ResourceManager.GetString("title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string title_warning {
            get {
                return ResourceManager.GetString("title_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFI Enterprise Solution.
        /// </summary>
        internal static string title_WebTitle {
            get {
                return ResourceManager.GetString("title_WebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string tt_AddNew {
            get {
                return ResourceManager.GetString("tt_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string tt_Back {
            get {
                return ResourceManager.GetString("tt_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse ...
        /// </summary>
        internal static string tt_BrowseTag {
            get {
                return ResourceManager.GetString("tt_BrowseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string tt_Cancel {
            get {
                return ResourceManager.GetString("tt_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status.
        /// </summary>
        internal static string tt_ChangeStatus {
            get {
                return ResourceManager.GetString("tt_ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string tt_Confirm {
            get {
                return ResourceManager.GetString("tt_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this item.
        /// </summary>
        internal static string tt_DeleteItem {
            get {
                return ResourceManager.GetString("tt_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable this record.
        /// </summary>
        internal static string tt_DisableRecord {
            get {
                return ResourceManager.GetString("tt_DisableRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to edit field.
        /// </summary>
        internal static string tt_DobleClickEdit {
            get {
                return ResourceManager.GetString("tt_DobleClickEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this row.
        /// </summary>
        internal static string tt_Edit {
            get {
                return ResourceManager.GetString("tt_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export information to Excel.
        /// </summary>
        internal static string tt_ExportToExcel {
            get {
                return ResourceManager.GetString("tt_ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to main page.
        /// </summary>
        internal static string tt_GoHome {
            get {
                return ResourceManager.GetString("tt_GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string tt_Reload {
            get {
                return ResourceManager.GetString("tt_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to list.
        /// </summary>
        internal static string tt_ReturnToList {
            get {
                return ResourceManager.GetString("tt_ReturnToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save information.
        /// </summary>
        internal static string tt_Save {
            get {
                return ResourceManager.GetString("tt_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test SMS.
        /// </summary>
        internal static string tt_TestSMS {
            get {
                return ResourceManager.GetString("tt_TestSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information.
        /// </summary>
        internal static string tt_UpdateInformation {
            get {
                return ResourceManager.GetString("tt_UpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect all.
        /// </summary>
        internal static string unselectAll {
            get {
                return ResourceManager.GetString("unselectAll", resourceCulture);
            }
        }
    }
}
