//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Defects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Defects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Defects", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string gvh_DefectColor {
            get {
                return ResourceManager.GetString("gvh_DefectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string gvh_DefectFontColor {
            get {
                return ResourceManager.GetString("gvh_DefectFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        internal static string gvh_DefectGoal {
            get {
                return ResourceManager.GetString("gvh_DefectGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string gvh_DefectName {
            get {
                return ResourceManager.GetString("gvh_DefectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string gvh_Design {
            get {
                return ResourceManager.GetString("gvh_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string gvh_ProductionLine {
            get {
                return ResourceManager.GetString("gvh_ProductionLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string gvh_ProductionProcess {
            get {
                return ResourceManager.GetString("gvh_ProductionProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string gvh_ShiftTag {
            get {
                return ResourceManager.GetString("gvh_ShiftTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA.
        /// </summary>
        internal static string gvh_VA {
            get {
                return ResourceManager.GetString("gvh_VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lbl_AddDefectDetailsTag {
            get {
                return ResourceManager.GetString("lbl_AddDefectDetailsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lbl_AD_AddDefectDetailsTag {
            get {
                return ResourceManager.GetString("lbl_AD_AddDefectDetailsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit goal.
        /// </summary>
        internal static string lbl_AD_EditViewHeaderTag {
            get {
                return ResourceManager.GetString("lbl_AD_EditViewHeaderTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add goal.
        /// </summary>
        internal static string lbl_AD_ViewHeaderTag {
            get {
                return ResourceManager.GetString("lbl_AD_ViewHeaderTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string lbl_DefectColorTag {
            get {
                return ResourceManager.GetString("lbl_DefectColorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        internal static string lbl_DefectName {
            get {
                return ResourceManager.GetString("lbl_DefectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string lbl_DesignTag {
            get {
                return ResourceManager.GetString("lbl_DesignTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string lbl_EditDefectDetailsTag {
            get {
                return ResourceManager.GetString("lbl_EditDefectDetailsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        internal static string lbl_FontColorTag {
            get {
                return ResourceManager.GetString("lbl_FontColorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        internal static string lbl_GoalTag {
            get {
                return ResourceManager.GetString("lbl_GoalTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure wish to delete the all defect detail ?.
        /// </summary>
        internal static string lbl_MsgDeleteDefectTag {
            get {
                return ResourceManager.GetString("lbl_MsgDeleteDefectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure wish to delete the defect detail ?.
        /// </summary>
        internal static string lbl_MsgDeleteDetailItemTag {
            get {
                return ResourceManager.GetString("lbl_MsgDeleteDetailItemTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string lbl_ProcessLineTag {
            get {
                return ResourceManager.GetString("lbl_ProcessLineTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string lbl_ProcessProductionTag {
            get {
                return ResourceManager.GetString("lbl_ProcessProductionTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA.
        /// </summary>
        internal static string lbl_VATag {
            get {
                return ResourceManager.GetString("lbl_VATag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defects.
        /// </summary>
        internal static string lbl_ViewHeaderTag {
            get {
                return ResourceManager.GetString("lbl_ViewHeaderTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add info details.
        /// </summary>
        internal static string tt_AddDefect {
            get {
                return ResourceManager.GetString("tt_AddDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all detail(s).
        /// </summary>
        internal static string tt_DeleteAllDetails {
            get {
                return ResourceManager.GetString("tt_DeleteAllDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete detail información.
        /// </summary>
        internal static string tt_DeleteDefectDetails {
            get {
                return ResourceManager.GetString("tt_DeleteDefectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit defect details.
        /// </summary>
        internal static string tt_EditDefectDetail {
            get {
                return ResourceManager.GetString("tt_EditDefectDetail", resourceCulture);
            }
        }
    }
}
