//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GenericCharts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericCharts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GenericCharts", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Axis.
        /// </summary>
        internal static string btn_NewAxis {
            get {
                return ResourceManager.GetString("btn_NewAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Chart.
        /// </summary>
        internal static string btn_NewChart {
            get {
                return ResourceManager.GetString("btn_NewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Filter.
        /// </summary>
        internal static string btn_NewFilter {
            get {
                return ResourceManager.GetString("btn_NewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area.
        /// </summary>
        internal static string lbl_Area {
            get {
                return ResourceManager.GetString("lbl_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Axis Categories.
        /// </summary>
        internal static string lbl_AxisCategories {
            get {
                return ResourceManager.GetString("lbl_AxisCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Axis Name.
        /// </summary>
        internal static string lbl_AxisName {
            get {
                return ResourceManager.GetString("lbl_AxisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a X Axis.
        /// </summary>
        internal static string lbl_AxisX {
            get {
                return ResourceManager.GetString("lbl_AxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalog.
        /// </summary>
        internal static string lbl_Catalog {
            get {
                return ResourceManager.GetString("lbl_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        internal static string lbl_Category {
            get {
                return ResourceManager.GetString("lbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chart Area.
        /// </summary>
        internal static string lbl_ChartArea {
            get {
                return ResourceManager.GetString("lbl_ChartArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chart Name.
        /// </summary>
        internal static string lbl_ChartName {
            get {
                return ResourceManager.GetString("lbl_ChartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available Charts By Area.
        /// </summary>
        internal static string lbl_ChartOfAreas {
            get {
                return ResourceManager.GetString("lbl_ChartOfAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available Areas.
        /// </summary>
        internal static string lbl_ChartsAreas {
            get {
                return ResourceManager.GetString("lbl_ChartsAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ChartType.
        /// </summary>
        internal static string lbl_ChartType {
            get {
                return ResourceManager.GetString("lbl_ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        internal static string lbl_Color {
            get {
                return ResourceManager.GetString("lbl_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chart Data.
        /// </summary>
        internal static string lbl_DataChart {
            get {
                return ResourceManager.GetString("lbl_DataChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Chart Axis.
        /// </summary>
        internal static string lbl_DataChartAxis {
            get {
                return ResourceManager.GetString("lbl_DataChartAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Chart Filters.
        /// </summary>
        internal static string lbl_DataChartFilters {
            get {
                return ResourceManager.GetString("lbl_DataChartFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Type.
        /// </summary>
        internal static string lbl_DataType {
            get {
                return ResourceManager.GetString("lbl_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Value.
        /// </summary>
        internal static string lbl_DefaultValue {
            get {
                return ResourceManager.GetString("lbl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter Categories.
        /// </summary>
        internal static string lbl_FilterCategories {
            get {
                return ResourceManager.GetString("lbl_FilterCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter Name.
        /// </summary>
        internal static string lbl_FilterName {
            get {
                return ResourceManager.GetString("lbl_FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filters Of Selected Chart.
        /// </summary>
        internal static string lbl_FiltersOfChart {
            get {
                return ResourceManager.GetString("lbl_FiltersOfChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font Background.
        /// </summary>
        internal static string lbl_FontBackgroundColor {
            get {
                return ResourceManager.GetString("lbl_FontBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font Color.
        /// </summary>
        internal static string lbl_FontColor {
            get {
                return ResourceManager.GetString("lbl_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font Size.
        /// </summary>
        internal static string lbl_FontSize {
            get {
                return ResourceManager.GetString("lbl_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format.
        /// </summary>
        internal static string lbl_Format {
            get {
                return ResourceManager.GetString("lbl_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format List.
        /// </summary>
        internal static string lbl_FormatList {
            get {
                return ResourceManager.GetString("lbl_FormatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format Preview.
        /// </summary>
        internal static string lbl_FormatPreview {
            get {
                return ResourceManager.GetString("lbl_FormatPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formula.
        /// </summary>
        internal static string lbl_Formula {
            get {
                return ResourceManager.GetString("lbl_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input Value.
        /// </summary>
        internal static string lbl_InputValue {
            get {
                return ResourceManager.GetString("lbl_InputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Label Format.
        /// </summary>
        internal static string lbl_LabelFormat {
            get {
                return ResourceManager.GetString("lbl_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotation angle.
        /// </summary>
        internal static string lbl_LabelRotation {
            get {
                return ResourceManager.GetString("lbl_LabelRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show.
        /// </summary>
        internal static string lbl_LabelShow {
            get {
                return ResourceManager.GetString("lbl_LabelShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List.
        /// </summary>
        internal static string lbl_List {
            get {
                return ResourceManager.GetString("lbl_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste your copied info here ( Ctrl + v ).
        /// </summary>
        internal static string lbl_PasteYourInfoHere {
            get {
                return ResourceManager.GetString("lbl_PasteYourInfoHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prefix.
        /// </summary>
        internal static string lbl_Prefix {
            get {
                return ResourceManager.GetString("lbl_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview Chart.
        /// </summary>
        internal static string lbl_PreviewChart {
            get {
                return ResourceManager.GetString("lbl_PreviewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Line.
        /// </summary>
        internal static string lbl_ShowLine {
            get {
                return ResourceManager.GetString("lbl_ShowLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sufix.
        /// </summary>
        internal static string lbl_Sufix {
            get {
                return ResourceManager.GetString("lbl_Sufix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string lbl_Title {
            get {
                return ResourceManager.GetString("lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        internal static string lbl_Type {
            get {
                return ResourceManager.GetString("lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Types.
        /// </summary>
        internal static string lbl_Types {
            get {
                return ResourceManager.GetString("lbl_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value.
        /// </summary>
        internal static string lbl_Value {
            get {
                return ResourceManager.GetString("lbl_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Axes are required for the chart..
        /// </summary>
        internal static string msg_ChartAxesRequired {
            get {
                return ResourceManager.GetString("msg_ChartAxesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The chart already contain data, do you want to overwrite it?.
        /// </summary>
        internal static string msg_ChartContainsData {
            get {
                return ResourceManager.GetString("msg_ChartContainsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filters are required for the chart..
        /// </summary>
        internal static string msg_ChartFiltersRequired {
            get {
                return ResourceManager.GetString("msg_ChartFiltersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the axis?.
        /// </summary>
        internal static string msg_ConfirmDeleteAxis {
            get {
                return ResourceManager.GetString("msg_ConfirmDeleteAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the filter?.
        /// </summary>
        internal static string msg_ConfirmDeleteFilter {
            get {
                return ResourceManager.GetString("msg_ConfirmDeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the chart?.
        /// </summary>
        internal static string msg_DeleteChartConfirm {
            get {
                return ResourceManager.GetString("msg_DeleteChartConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The filter category is required.
        /// </summary>
        internal static string msg_FilterCategoryRequired {
            get {
                return ResourceManager.GetString("msg_FilterCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must choose a formula for the filter.
        /// </summary>
        internal static string msg_FilterFormulaRequired {
            get {
                return ResourceManager.GetString("msg_FilterFormulaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The filter name is required.
        /// </summary>
        internal static string msg_FilterNameRequired {
            get {
                return ResourceManager.GetString("msg_FilterNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must choose a list for the filter.
        /// </summary>
        internal static string msg_FilterTypeListRequired {
            get {
                return ResourceManager.GetString("msg_FilterTypeListRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must choose a value for the filter.
        /// </summary>
        internal static string msg_FilterValueRequired {
            get {
                return ResourceManager.GetString("msg_FilterValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You do not have information to graph, please add data.
        /// </summary>
        internal static string msg_PreviewChartEmptyData {
            get {
                return ResourceManager.GetString("msg_PreviewChartEmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This graph already has an assigned x axis.
        /// </summary>
        internal static string msg_xAxisExist {
            get {
                return ResourceManager.GetString("msg_xAxisExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chart Preview.
        /// </summary>
        internal static string title_ChartPreview {
            get {
                return ResourceManager.GetString("title_ChartPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chart Data Administrator.
        /// </summary>
        internal static string title_DataChartAdmin {
            get {
                return ResourceManager.GetString("title_DataChartAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Axis.
        /// </summary>
        internal static string title_EditAxis {
            get {
                return ResourceManager.GetString("title_EditAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Chart.
        /// </summary>
        internal static string title_EditChart {
            get {
                return ResourceManager.GetString("title_EditChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Filter.
        /// </summary>
        internal static string title_EditFilter {
            get {
                return ResourceManager.GetString("title_EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Axis.
        /// </summary>
        internal static string title_NewAxis {
            get {
                return ResourceManager.GetString("title_NewAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Chart.
        /// </summary>
        internal static string title_NewChart {
            get {
                return ResourceManager.GetString("title_NewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Filter.
        /// </summary>
        internal static string title_NewFilter {
            get {
                return ResourceManager.GetString("title_NewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Axis.
        /// </summary>
        internal static string tooltip_DeleteAxis {
            get {
                return ResourceManager.GetString("tooltip_DeleteAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Chart.
        /// </summary>
        internal static string tooltip_DeleteChart {
            get {
                return ResourceManager.GetString("tooltip_DeleteChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Filter.
        /// </summary>
        internal static string tooltip_DeleteFilter {
            get {
                return ResourceManager.GetString("tooltip_DeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Axis.
        /// </summary>
        internal static string tooltip_EditAxis {
            get {
                return ResourceManager.GetString("tooltip_EditAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Chart.
        /// </summary>
        internal static string tooltip_EditChart {
            get {
                return ResourceManager.GetString("tooltip_EditChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Filter.
        /// </summary>
        internal static string tooltip_EditFilter {
            get {
                return ResourceManager.GetString("tooltip_EditFilter", resourceCulture);
            }
        }
    }
}
