//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GenericCharts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericCharts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GenericCharts", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Axis.
        /// </summary>
        internal static string btn_NewAxis {
            get {
                return ResourceManager.GetString("btn_NewAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Chart.
        /// </summary>
        internal static string btn_NewChart {
            get {
                return ResourceManager.GetString("btn_NewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Filter.
        /// </summary>
        internal static string btn_NewFilter {
            get {
                return ResourceManager.GetString("btn_NewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string lbl_Area {
            get {
                return ResourceManager.GetString("lbl_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Categories.
        /// </summary>
        internal static string lbl_AxisCategories {
            get {
                return ResourceManager.GetString("lbl_AxisCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Name.
        /// </summary>
        internal static string lbl_AxisName {
            get {
                return ResourceManager.GetString("lbl_AxisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis.
        /// </summary>
        internal static string lbl_AxisX {
            get {
                return ResourceManager.GetString("lbl_AxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string lbl_Catalog {
            get {
                return ResourceManager.GetString("lbl_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string lbl_Category {
            get {
                return ResourceManager.GetString("lbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Area.
        /// </summary>
        internal static string lbl_ChartArea {
            get {
                return ResourceManager.GetString("lbl_ChartArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Name.
        /// </summary>
        internal static string lbl_ChartName {
            get {
                return ResourceManager.GetString("lbl_ChartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Charts By Area.
        /// </summary>
        internal static string lbl_ChartOfAreas {
            get {
                return ResourceManager.GetString("lbl_ChartOfAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Areas.
        /// </summary>
        internal static string lbl_ChartsAreas {
            get {
                return ResourceManager.GetString("lbl_ChartsAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChartType.
        /// </summary>
        internal static string lbl_ChartType {
            get {
                return ResourceManager.GetString("lbl_ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string lbl_Color {
            get {
                return ResourceManager.GetString("lbl_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Data.
        /// </summary>
        internal static string lbl_DataChart {
            get {
                return ResourceManager.GetString("lbl_DataChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Chart Axis.
        /// </summary>
        internal static string lbl_DataChartAxis {
            get {
                return ResourceManager.GetString("lbl_DataChartAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Chart Filters.
        /// </summary>
        internal static string lbl_DataChartFilters {
            get {
                return ResourceManager.GetString("lbl_DataChartFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string lbl_DataType {
            get {
                return ResourceManager.GetString("lbl_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string lbl_DefaultValue {
            get {
                return ResourceManager.GetString("lbl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Categories.
        /// </summary>
        internal static string lbl_FilterCategories {
            get {
                return ResourceManager.GetString("lbl_FilterCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Name.
        /// </summary>
        internal static string lbl_FilterName {
            get {
                return ResourceManager.GetString("lbl_FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters Of Selected Chart.
        /// </summary>
        internal static string lbl_FiltersOfChart {
            get {
                return ResourceManager.GetString("lbl_FiltersOfChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Background.
        /// </summary>
        internal static string lbl_FontBackgroundColor {
            get {
                return ResourceManager.GetString("lbl_FontBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        internal static string lbl_FontColor {
            get {
                return ResourceManager.GetString("lbl_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string lbl_FontSize {
            get {
                return ResourceManager.GetString("lbl_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string lbl_Format {
            get {
                return ResourceManager.GetString("lbl_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format List.
        /// </summary>
        internal static string lbl_FormatList {
            get {
                return ResourceManager.GetString("lbl_FormatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Preview.
        /// </summary>
        internal static string lbl_FormatPreview {
            get {
                return ResourceManager.GetString("lbl_FormatPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        internal static string lbl_Formula {
            get {
                return ResourceManager.GetString("lbl_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Value.
        /// </summary>
        internal static string lbl_InputValue {
            get {
                return ResourceManager.GetString("lbl_InputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Format.
        /// </summary>
        internal static string lbl_LabelFormat {
            get {
                return ResourceManager.GetString("lbl_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation angle.
        /// </summary>
        internal static string lbl_LabelRotation {
            get {
                return ResourceManager.GetString("lbl_LabelRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string lbl_LabelShow {
            get {
                return ResourceManager.GetString("lbl_LabelShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string lbl_List {
            get {
                return ResourceManager.GetString("lbl_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste your copied info here ( Ctrl + v ).
        /// </summary>
        internal static string lbl_PasteYourInfoHere {
            get {
                return ResourceManager.GetString("lbl_PasteYourInfoHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string lbl_Prefix {
            get {
                return ResourceManager.GetString("lbl_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Chart.
        /// </summary>
        internal static string lbl_PreviewChart {
            get {
                return ResourceManager.GetString("lbl_PreviewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Line.
        /// </summary>
        internal static string lbl_ShowLine {
            get {
                return ResourceManager.GetString("lbl_ShowLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sufix.
        /// </summary>
        internal static string lbl_Sufix {
            get {
                return ResourceManager.GetString("lbl_Sufix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lbl_Title {
            get {
                return ResourceManager.GetString("lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lbl_Type {
            get {
                return ResourceManager.GetString("lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        internal static string lbl_Types {
            get {
                return ResourceManager.GetString("lbl_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string lbl_Value {
            get {
                return ResourceManager.GetString("lbl_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes are required for the chart..
        /// </summary>
        internal static string msg_ChartAxesRequired {
            get {
                return ResourceManager.GetString("msg_ChartAxesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart already contain data, do you want to overwrite it?.
        /// </summary>
        internal static string msg_ChartContainsData {
            get {
                return ResourceManager.GetString("msg_ChartContainsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters are required for the chart..
        /// </summary>
        internal static string msg_ChartFiltersRequired {
            get {
                return ResourceManager.GetString("msg_ChartFiltersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the axis?.
        /// </summary>
        internal static string msg_ConfirmDeleteAxis {
            get {
                return ResourceManager.GetString("msg_ConfirmDeleteAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the filter?.
        /// </summary>
        internal static string msg_ConfirmDeleteFilter {
            get {
                return ResourceManager.GetString("msg_ConfirmDeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the chart?.
        /// </summary>
        internal static string msg_DeleteChartConfirm {
            get {
                return ResourceManager.GetString("msg_DeleteChartConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter category is required.
        /// </summary>
        internal static string msg_FilterCategoryRequired {
            get {
                return ResourceManager.GetString("msg_FilterCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose a formula for the filter.
        /// </summary>
        internal static string msg_FilterFormulaRequired {
            get {
                return ResourceManager.GetString("msg_FilterFormulaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter name is required.
        /// </summary>
        internal static string msg_FilterNameRequired {
            get {
                return ResourceManager.GetString("msg_FilterNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose a list for the filter.
        /// </summary>
        internal static string msg_FilterTypeListRequired {
            get {
                return ResourceManager.GetString("msg_FilterTypeListRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose a value for the filter.
        /// </summary>
        internal static string msg_FilterValueRequired {
            get {
                return ResourceManager.GetString("msg_FilterValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have information to graph, please add data.
        /// </summary>
        internal static string msg_PreviewChartEmptyData {
            get {
                return ResourceManager.GetString("msg_PreviewChartEmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This graph already has an assigned x axis.
        /// </summary>
        internal static string msg_xAxisExist {
            get {
                return ResourceManager.GetString("msg_xAxisExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Preview.
        /// </summary>
        internal static string title_ChartPreview {
            get {
                return ResourceManager.GetString("title_ChartPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Data Administrator.
        /// </summary>
        internal static string title_DataChartAdmin {
            get {
                return ResourceManager.GetString("title_DataChartAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Axis.
        /// </summary>
        internal static string title_EditAxis {
            get {
                return ResourceManager.GetString("title_EditAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Chart.
        /// </summary>
        internal static string title_EditChart {
            get {
                return ResourceManager.GetString("title_EditChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Filter.
        /// </summary>
        internal static string title_EditFilter {
            get {
                return ResourceManager.GetString("title_EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Axis.
        /// </summary>
        internal static string title_NewAxis {
            get {
                return ResourceManager.GetString("title_NewAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Chart.
        /// </summary>
        internal static string title_NewChart {
            get {
                return ResourceManager.GetString("title_NewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Filter.
        /// </summary>
        internal static string title_NewFilter {
            get {
                return ResourceManager.GetString("title_NewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Axis.
        /// </summary>
        internal static string tooltip_DeleteAxis {
            get {
                return ResourceManager.GetString("tooltip_DeleteAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Chart.
        /// </summary>
        internal static string tooltip_DeleteChart {
            get {
                return ResourceManager.GetString("tooltip_DeleteChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Filter.
        /// </summary>
        internal static string tooltip_DeleteFilter {
            get {
                return ResourceManager.GetString("tooltip_DeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Axis.
        /// </summary>
        internal static string tooltip_EditAxis {
            get {
                return ResourceManager.GetString("tooltip_EditAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Chart.
        /// </summary>
        internal static string tooltip_EditChart {
            get {
                return ResourceManager.GetString("tooltip_EditChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Filter.
        /// </summary>
        internal static string tooltip_EditFilter {
            get {
                return ResourceManager.GetString("tooltip_EditFilter", resourceCulture);
            }
        }
    }
}
