//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MFG {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MoldFamilies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MoldFamilies() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MFG.MoldFamilies", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update From Excel.
        /// </summary>
        internal static string btn_UpdateFromExcel {
            get {
                return ResourceManager.GetString("btn_UpdateFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family Name.
        /// </summary>
        internal static string lbl_FamilyName {
            get {
                return ResourceManager.GetString("lbl_FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lens.
        /// </summary>
        internal static string lbl_Lens {
            get {
                return ResourceManager.GetString("lbl_Lens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LensTypes.
        /// </summary>
        internal static string lbl_LensTypes {
            get {
                return ResourceManager.GetString("lbl_LensTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Len Types.
        /// </summary>
        internal static string lbl_LenTypes {
            get {
                return ResourceManager.GetString("lbl_LenTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are sure you want to delete the len type?.
        /// </summary>
        internal static string msg_DeleteLenTypeRecordConfirm {
            get {
                return ResourceManager.GetString("msg_DeleteLenTypeRecordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are sure you want to delete the mold family?.
        /// </summary>
        internal static string msg_DeleteMoldFamilyRecordConfirm {
            get {
                return ResourceManager.GetString("msg_DeleteMoldFamilyRecordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information has been updated.
        /// </summary>
        internal static string msg_ExcelImportMessage {
            get {
                return ResourceManager.GetString("msg_ExcelImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This type of lens is already assigned.
        /// </summary>
        internal static string msg_LenTypeAlreadyAssigned {
            get {
                return ResourceManager.GetString("msg_LenTypeAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot delete this record, the family must have at least one type of lens..
        /// </summary>
        internal static string msg_LenTypesRequiredInTable {
            get {
                return ResourceManager.GetString("msg_LenTypesRequiredInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mold family was deleted successfully.
        /// </summary>
        internal static string msg_MoldFamilyDeleted {
            get {
                return ResourceManager.GetString("msg_MoldFamilyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a lens type.
        /// </summary>
        internal static string msg_SelectLensType {
            get {
                return ResourceManager.GetString("msg_SelectLensType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mold Families List.
        /// </summary>
        internal static string title_MoldFamiliesList {
            get {
                return ResourceManager.GetString("title_MoldFamiliesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Mold Family.
        /// </summary>
        internal static string title_NewMoldFamily {
            get {
                return ResourceManager.GetString("title_NewMoldFamily", resourceCulture);
            }
        }
    }
}
