//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MFG {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MachineSetups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MachineSetups() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MFG.MachineSetups", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Section.
        /// </summary>
        internal static string btn_AddSection {
            get {
                return ResourceManager.GetString("btn_AddSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Setup.
        /// </summary>
        internal static string btn_New_Setup {
            get {
                return ResourceManager.GetString("btn_New_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string btn_Search {
            get {
                return ResourceManager.GetString("btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Parameter.
        /// </summary>
        internal static string lbl_AddParameter {
            get {
                return ResourceManager.GetString("lbl_AddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Setup Parameter.
        /// </summary>
        internal static string lbl_AddSetupParameter {
            get {
                return ResourceManager.GetString("lbl_AddSetupParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalog List.
        /// </summary>
        internal static string lbl_CatalogList {
            get {
                return ResourceManager.GetString("lbl_CatalogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seconds.
        /// </summary>
        internal static string lbl_CycleTimeUom {
            get {
                return ResourceManager.GetString("lbl_CycleTimeUom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Setup.
        /// </summary>
        internal static string lbl_EditSetup {
            get {
                return ResourceManager.GetString("lbl_EditSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        internal static string lbl_Enable {
            get {
                return ResourceManager.GetString("lbl_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        internal static string lbl_Enabled {
            get {
                return ResourceManager.GetString("lbl_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filters.
        /// </summary>
        internal static string lbl_Filters {
            get {
                return ResourceManager.GetString("lbl_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General Information.
        /// </summary>
        internal static string lbl_GeneralInfo {
            get {
                return ResourceManager.GetString("lbl_GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Alert?.
        /// </summary>
        internal static string lbl_IsAlert {
            get {
                return ResourceManager.GetString("lbl_IsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Calculated.
        /// </summary>
        internal static string lbl_IsCalculated {
            get {
                return ResourceManager.GetString("lbl_IsCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Cavity?.
        /// </summary>
        internal static string lbl_IsCavity {
            get {
                return ResourceManager.GetString("lbl_IsCavity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length.
        /// </summary>
        internal static string lbl_Length {
            get {
                return ResourceManager.GetString("lbl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Machine.
        /// </summary>
        internal static string lbl_Machine {
            get {
                return ResourceManager.GetString("lbl_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Machine Categories.
        /// </summary>
        internal static string lbl_MachineCategories {
            get {
                return ResourceManager.GetString("lbl_MachineCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Machine Category.
        /// </summary>
        internal static string lbl_MachineCategory {
            get {
                return ResourceManager.GetString("lbl_MachineCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Machine Description.
        /// </summary>
        internal static string lbl_MachineDesccription {
            get {
                return ResourceManager.GetString("lbl_MachineDesccription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Machine/Materials.
        /// </summary>
        internal static string lbl_MachineMaterials {
            get {
                return ResourceManager.GetString("lbl_MachineMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Machine Name.
        /// </summary>
        internal static string lbl_MachineName {
            get {
                return ResourceManager.GetString("lbl_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Mandatory?.
        /// </summary>
        internal static string lbl_Mandatory {
            get {
                return ResourceManager.GetString("lbl_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material.
        /// </summary>
        internal static string lbl_Material {
            get {
                return ResourceManager.GetString("lbl_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max.
        /// </summary>
        internal static string lbl_Max {
            get {
                return ResourceManager.GetString("lbl_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max is Formula?.
        /// </summary>
        internal static string lbl_MaxIsFormula {
            get {
                return ResourceManager.GetString("lbl_MaxIsFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Min.
        /// </summary>
        internal static string lbl_Min {
            get {
                return ResourceManager.GetString("lbl_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Min is Formula?.
        /// </summary>
        internal static string lbl_MinIsFormula {
            get {
                return ResourceManager.GetString("lbl_MinIsFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Machine.
        /// </summary>
        internal static string lbl_NewMachine {
            get {
                return ResourceManager.GetString("lbl_NewMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Material.
        /// </summary>
        internal static string lbl_NewMaterial {
            get {
                return ResourceManager.GetString("lbl_NewMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Parameter.
        /// </summary>
        internal static string lbl_NewParameter {
            get {
                return ResourceManager.GetString("lbl_NewParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Section.
        /// </summary>
        internal static string lbl_NewSection {
            get {
                return ResourceManager.GetString("lbl_NewSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Machine Setup.
        /// </summary>
        internal static string lbl_New_Machine_Setup {
            get {
                return ResourceManager.GetString("lbl_New_Machine_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numeric Value.
        /// </summary>
        internal static string lbl_NumericValue {
            get {
                return ResourceManager.GetString("lbl_NumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operator.
        /// </summary>
        internal static string lbl_Operator {
            get {
                return ResourceManager.GetString("lbl_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        internal static string lbl_Options {
            get {
                return ResourceManager.GetString("lbl_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameter.
        /// </summary>
        internal static string lbl_Parameter {
            get {
                return ResourceManager.GetString("lbl_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameter Formula.
        /// </summary>
        internal static string lbl_ParameterFormula {
            get {
                return ResourceManager.GetString("lbl_ParameterFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameters.
        /// </summary>
        internal static string lbl_Parameters {
            get {
                return ResourceManager.GetString("lbl_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of Decimals.
        /// </summary>
        internal static string lbl_Precition {
            get {
                return ResourceManager.GetString("lbl_Precition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Production Line.
        /// </summary>
        internal static string lbl_ProductionLine {
            get {
                return ResourceManager.GetString("lbl_ProductionLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reference.
        /// </summary>
        internal static string lbl_Reference {
            get {
                return ResourceManager.GetString("lbl_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reference List.
        /// </summary>
        internal static string lbl_ReferenceList {
            get {
                return ResourceManager.GetString("lbl_ReferenceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Section.
        /// </summary>
        internal static string lbl_Section {
            get {
                return ResourceManager.GetString("lbl_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string lbl_SectionDescription {
            get {
                return ResourceManager.GetString("lbl_SectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Section Name.
        /// </summary>
        internal static string lbl_SectionName {
            get {
                return ResourceManager.GetString("lbl_SectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Machine.
        /// </summary>
        internal static string lbl_SelectMachine {
            get {
                return ResourceManager.GetString("lbl_SelectMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Material.
        /// </summary>
        internal static string lbl_SelectMaterial {
            get {
                return ResourceManager.GetString("lbl_SelectMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Parameter.
        /// </summary>
        internal static string lbl_SelectParameter {
            get {
                return ResourceManager.GetString("lbl_SelectParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Section.
        /// </summary>
        internal static string lbl_SelectSection {
            get {
                return ResourceManager.GetString("lbl_SelectSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setup.
        /// </summary>
        internal static string lbl_Setup {
            get {
                return ResourceManager.GetString("lbl_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Machine Setup.
        /// </summary>
        internal static string lbl_Title {
            get {
                return ResourceManager.GetString("lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        internal static string lbl_Type {
            get {
                return ResourceManager.GetString("lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UoM.
        /// </summary>
        internal static string lbl_UoM {
            get {
                return ResourceManager.GetString("lbl_UoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use Reference.
        /// </summary>
        internal static string lbl_UseReference {
            get {
                return ResourceManager.GetString("lbl_UseReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value.
        /// </summary>
        internal static string lbl_Value {
            get {
                return ResourceManager.GetString("lbl_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value Formula.
        /// </summary>
        internal static string lbl_ValueFormula {
            get {
                return ResourceManager.GetString("lbl_ValueFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value is Formula?.
        /// </summary>
        internal static string lbl_ValueIsFormula {
            get {
                return ResourceManager.GetString("lbl_ValueIsFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Values.
        /// </summary>
        internal static string lbl_Values {
            get {
                return ResourceManager.GetString("lbl_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the defect?.
        /// </summary>
        internal static string msg_ConfirmToDeleteDefect {
            get {
                return ResourceManager.GetString("msg_ConfirmToDeleteDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the downtime?.
        /// </summary>
        internal static string msg_ConfirmToDeleteDowntime {
            get {
                return ResourceManager.GetString("msg_ConfirmToDeleteDowntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the gasket?.
        /// </summary>
        internal static string msg_ConfirmToDeleteGasket {
            get {
                return ResourceManager.GetString("msg_ConfirmToDeleteGasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the machine?.
        /// </summary>
        internal static string msg_ConfirmToDeleteMachine {
            get {
                return ResourceManager.GetString("msg_ConfirmToDeleteMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the machine parameter?.
        /// </summary>
        internal static string msg_ConfirmToDeleteMachineParameter {
            get {
                return ResourceManager.GetString("msg_ConfirmToDeleteMachineParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not leave the Cycle Time empty.
        /// </summary>
        internal static string msg_CycleTimeIsMandatory {
            get {
                return ResourceManager.GetString("msg_CycleTimeIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The material is already exist..
        /// </summary>
        internal static string msg_DuplicatedMaterial {
            get {
                return ResourceManager.GetString("msg_DuplicatedMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The name and description must have data..
        /// </summary>
        internal static string msg_MachDescObligtory {
            get {
                return ResourceManager.GetString("msg_MachDescObligtory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The material for that machine is already assigned.
        /// </summary>
        internal static string msg_MachineMaterialRepeat {
            get {
                return ResourceManager.GetString("msg_MachineMaterialRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a machine and a material..
        /// </summary>
        internal static string msg_MachMatMandatory {
            get {
                return ResourceManager.GetString("msg_MachMatMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The minimum amount can not be greater than the maximum..
        /// </summary>
        internal static string msg_MinMaxInvalid {
            get {
                return ResourceManager.GetString("msg_MinMaxInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not leave the name field empty.
        /// </summary>
        internal static string msg_NameMandatory {
            get {
                return ResourceManager.GetString("msg_NameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must assign at least one material..
        /// </summary>
        internal static string msg_NoMaterial {
            get {
                return ResourceManager.GetString("msg_NoMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must assign at least one parameter..
        /// </summary>
        internal static string msg_NoParameter {
            get {
                return ResourceManager.GetString("msg_NoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameter is already assigned to this setup.
        /// </summary>
        internal static string msg_ParameterExistInTable {
            get {
                return ResourceManager.GetString("msg_ParameterExistInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The formula was correctly assigned to the parameter .
        /// </summary>
        internal static string msg_ParameterFormulaAdded {
            get {
                return ResourceManager.GetString("msg_ParameterFormulaAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The formula does not have the correct format.
        /// </summary>
        internal static string msg_ParameterFormulaError {
            get {
                return ResourceManager.GetString("msg_ParameterFormulaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of decimals can not be greater than the length.
        /// </summary>
        internal static string msg_PrecitionLengthInvalid {
            get {
                return ResourceManager.GetString("msg_PrecitionLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The precision can not be greater than the length..
        /// </summary>
        internal static string msg_PrecitionLengthValidation {
            get {
                return ResourceManager.GetString("msg_PrecitionLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must choose a production process..
        /// </summary>
        internal static string msg_ProductionProcessMandatory {
            get {
                return ResourceManager.GetString("msg_ProductionProcessMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The max value field is required.
        /// </summary>
        internal static string msg_RequiredMaxValue {
            get {
                return ResourceManager.GetString("msg_RequiredMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The min value field is required.
        /// </summary>
        internal static string msg_RequiredMinValue {
            get {
                return ResourceManager.GetString("msg_RequiredMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The parameter field is required.
        /// </summary>
        internal static string msg_RequiredParameter {
            get {
                return ResourceManager.GetString("msg_RequiredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The section field is required.
        /// </summary>
        internal static string msg_RequiredSection {
            get {
                return ResourceManager.GetString("msg_RequiredSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The UoM field is required.
        /// </summary>
        internal static string msg_RequiredUoM {
            get {
                return ResourceManager.GetString("msg_RequiredUoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The machine parameter edited has been saved successfully..
        /// </summary>
        internal static string msg_SuccessEditParameter {
            get {
                return ResourceManager.GetString("msg_SuccessEditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new machine has been saved succesfully..
        /// </summary>
        internal static string msg_SuccessSaveMachine {
            get {
                return ResourceManager.GetString("msg_SuccessSaveMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new material has been saved succesfully..
        /// </summary>
        internal static string msg_SuccessSaveMaterial {
            get {
                return ResourceManager.GetString("msg_SuccessSaveMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new parameter has been saved succesfully..
        /// </summary>
        internal static string msg_SuccessSaveParameter {
            get {
                return ResourceManager.GetString("msg_SuccessSaveParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new section has been saved succesfully..
        /// </summary>
        internal static string msg_SuccessSaveSection {
            get {
                return ResourceManager.GetString("msg_SuccessSaveSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The configuration has been saved successfully..
        /// </summary>
        internal static string msg_SuccessSaveSetup {
            get {
                return ResourceManager.GetString("msg_SuccessSaveSetup", resourceCulture);
            }
        }
    }
}
