//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MFG {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MFG.Reports", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attendant.
        /// </summary>
        internal static string lbl_Attendant {
            get {
                return ResourceManager.GetString("lbl_Attendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cavities.
        /// </summary>
        internal static string lbl_Cavities {
            get {
                return ResourceManager.GetString("lbl_Cavities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date type.
        /// </summary>
        internal static string lbl_DateType {
            get {
                return ResourceManager.GetString("lbl_DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End Date time.
        /// </summary>
        internal static string lbl_EndDatetime {
            get {
                return ResourceManager.GetString("lbl_EndDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export.
        /// </summary>
        internal static string lbl_Export {
            get {
                return ResourceManager.GetString("lbl_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gaskets.
        /// </summary>
        internal static string lbl_Gaskets {
            get {
                return ResourceManager.GetString("lbl_Gaskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Within specification?.
        /// </summary>
        internal static string lbl_IsGood {
            get {
                return ResourceManager.GetString("lbl_IsGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Machines.
        /// </summary>
        internal static string lbl_Machines {
            get {
                return ResourceManager.GetString("lbl_Machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Materials.
        /// </summary>
        internal static string lbl_Materials {
            get {
                return ResourceManager.GetString("lbl_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameters.
        /// </summary>
        internal static string lbl_Parameters {
            get {
                return ResourceManager.GetString("lbl_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameters for.
        /// </summary>
        internal static string lbl_ParametersFor {
            get {
                return ResourceManager.GetString("lbl_ParametersFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Process.
        /// </summary>
        internal static string lbl_Process {
            get {
                return ResourceManager.GetString("lbl_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actions Reports.
        /// </summary>
        internal static string lbl_Report_ACT {
            get {
                return ResourceManager.GetString("lbl_Report_ACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EER Details Report.
        /// </summary>
        internal static string lbl_Report_EERDTLS {
            get {
                return ResourceManager.GetString("lbl_Report_EERDTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report Gasket Diameter.
        /// </summary>
        internal static string lbl_Report_GSKTDIAM {
            get {
                return ResourceManager.GetString("lbl_Report_GSKTDIAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameters Report.
        /// </summary>
        internal static string lbl_Report_PRMS {
            get {
                return ResourceManager.GetString("lbl_Report_PRMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsibles.
        /// </summary>
        internal static string lbl_Responsibles {
            get {
                return ResourceManager.GetString("lbl_Responsibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setups.
        /// </summary>
        internal static string lbl_Setups {
            get {
                return ResourceManager.GetString("lbl_Setups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shifts.
        /// </summary>
        internal static string lbl_Shifts {
            get {
                return ResourceManager.GetString("lbl_Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Date time.
        /// </summary>
        internal static string lbl_StartDatetime {
            get {
                return ResourceManager.GetString("lbl_StartDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        internal static string lbl_Status {
            get {
                return ResourceManager.GetString("lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reports.
        /// </summary>
        internal static string title_Reports {
            get {
                return ResourceManager.GetString("title_Reports", resourceCulture);
            }
        }
    }
}
