//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MFG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemoldDefects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoldDefects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MFG.DemoldDefects", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Scheduled Families.
        /// </summary>
        internal static string btn_ShowScheduledFamilies {
            get {
                return ResourceManager.GetString("btn_ShowScheduledFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adition.
        /// </summary>
        internal static string lbl_Adition {
            get {
                return ResourceManager.GetString("lbl_Adition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adition Category.
        /// </summary>
        internal static string lbl_AditionCategory {
            get {
                return ResourceManager.GetString("lbl_AditionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen product is in the system but is not in production, do you want to add a defect even so?.
        /// </summary>
        internal static string lbl_AlertMessageText {
            get {
                return ResourceManager.GetString("lbl_AlertMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string lbl_AlertMessageTitle {
            get {
                return ResourceManager.GetString("lbl_AlertMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string lbl_Base {
            get {
                return ResourceManager.GetString("lbl_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Category.
        /// </summary>
        internal static string lbl_BaseCategory {
            get {
                return ResourceManager.GetString("lbl_BaseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this if you prefer to enter the amount.
        /// </summary>
        internal static string lbl_CheckThisManualAmount {
            get {
                return ResourceManager.GetString("lbl_CheckThisManualAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        internal static string lbl_Defect {
            get {
                return ResourceManager.GetString("lbl_Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Type.
        /// </summary>
        internal static string lbl_DefectType {
            get {
                return ResourceManager.GetString("lbl_DefectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demold Defects.
        /// </summary>
        internal static string lbl_DemoldDefects {
            get {
                return ResourceManager.GetString("lbl_DemoldDefects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string lbl_Design {
            get {
                return ResourceManager.GetString("lbl_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string lbl_Family {
            get {
                return ResourceManager.GetString("lbl_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector.
        /// </summary>
        internal static string lbl_Inspector {
            get {
                return ResourceManager.GetString("lbl_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens Type Production.
        /// </summary>
        internal static string lbl_LensTypeProdQty {
            get {
                return ResourceManager.GetString("lbl_LensTypeProdQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Len Type.
        /// </summary>
        internal static string lbl_LenType {
            get {
                return ResourceManager.GetString("lbl_LenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Additions).
        /// </summary>
        internal static string lbl_NoAddition {
            get {
                return ResourceManager.GetString("lbl_NoAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Qty.
        /// </summary>
        internal static string lbl_PlanningQty {
            get {
                return ResourceManager.GetString("lbl_PlanningQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Process.
        /// </summary>
        internal static string lbl_ProductionProcess {
            get {
                return ResourceManager.GetString("lbl_ProductionProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string lbl_Quantity {
            get {
                return ResourceManager.GetString("lbl_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        internal static string lbl_Side {
            get {
                return ResourceManager.GetString("lbl_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the amount here.
        /// </summary>
        internal static string lbl_TextboxDefectQty {
            get {
                return ResourceManager.GetString("lbl_TextboxDefectQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no product with the chosen combination, try another..
        /// </summary>
        internal static string msg_CombinationProductNotExists {
            get {
                return ResourceManager.GetString("msg_CombinationProductNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a defect.
        /// </summary>
        internal static string msg_DefectRequired {
            get {
                return ResourceManager.GetString("msg_DefectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This VAT has no products in Production, you can press &quot;Show All&quot; to see all products.
        /// </summary>
        internal static string msg_ProductionFamilyNothing {
            get {
                return ResourceManager.GetString("msg_ProductionFamilyNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This VAT number has the product {0} in production but is not in the catalog.
        /// </summary>
        internal static string msg_ProductionFamilyNotInCatalog {
            get {
                return ResourceManager.GetString("msg_ProductionFamilyNotInCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all fields to continue.
        /// </summary>
        internal static string msg_SelectAllFields {
            get {
                return ResourceManager.GetString("msg_SelectAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or register of User.
        /// </summary>
        internal static string title_LoginRegister {
            get {
                return ResourceManager.GetString("title_LoginRegister", resourceCulture);
            }
        }
    }
}
