//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MFG_Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MFG_Dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSite.App_GlobalResources.MFG.Dashboard", typeof(MFG_Dashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string btn_ExportToExcel {
            get {
                return ResourceManager.GetString("btn_ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Plan.
        /// </summary>
        public static string lbl_actionplan {
            get {
                return ResourceManager.GetString("lbl_actionplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Code.
        /// </summary>
        public static string lbl_DayCode {
            get {
                return ResourceManager.GetString("lbl_DayCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downtimes.
        /// </summary>
        public static string lbl_Downtimes {
            get {
                return ResourceManager.GetString("lbl_Downtimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EER vs Downtimes.
        /// </summary>
        public static string lbl_EER_vs_Downtimes {
            get {
                return ResourceManager.GetString("lbl_EER_vs_Downtimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string lbl_Fullscreen {
            get {
                return ResourceManager.GetString("lbl_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Parameters.
        /// </summary>
        public static string lbl_ListofParameters {
            get {
                return ResourceManager.GetString("lbl_ListofParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string lbl_Machine {
            get {
                return ResourceManager.GetString("lbl_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines.
        /// </summary>
        public static string lbl_Machines {
            get {
                return ResourceManager.GetString("lbl_Machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string lbl_Materials {
            get {
                return ResourceManager.GetString("lbl_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string lbl_Max {
            get {
                return ResourceManager.GetString("lbl_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string lbl_Min {
            get {
                return ResourceManager.GetString("lbl_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of SPEC.
        /// </summary>
        public static string lbl_outofspec {
            get {
                return ResourceManager.GetString("lbl_outofspec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string lbl_Parameters {
            get {
                return ResourceManager.GetString("lbl_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string lbl_Plant {
            get {
                return ResourceManager.GetString("lbl_Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Description.
        /// </summary>
        public static string lbl_ProblemDescription {
            get {
                return ResourceManager.GetString("lbl_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string lbl_Process {
            get {
                return ResourceManager.GetString("lbl_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Rate.
        /// </summary>
        public static string lbl_ProductionRate {
            get {
                return ResourceManager.GetString("lbl_ProductionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string lbl_Responsible {
            get {
                return ResourceManager.GetString("lbl_Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string lbl_Shift {
            get {
                return ResourceManager.GetString("lbl_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary for Machine.
        /// </summary>
        public static string lbl_SummaryMachine {
            get {
                return ResourceManager.GetString("lbl_SummaryMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Parameters.
        /// </summary>
        public static string lbl_TableParameters {
            get {
                return ResourceManager.GetString("lbl_TableParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string lbl_TargetDate {
            get {
                return ResourceManager.GetString("lbl_TargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Parameters.
        /// </summary>
        public static string lbl_TotalParameters {
            get {
                return ResourceManager.GetString("lbl_TotalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string lbl_Value {
            get {
                return ResourceManager.GetString("lbl_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield vs Defects.
        /// </summary>
        public static string lbl_Yield_vs_Defects {
            get {
                return ResourceManager.GetString("lbl_Yield_vs_Defects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasket Production.
        /// </summary>
        public static string title_Charts {
            get {
                return ResourceManager.GetString("title_Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESS CONTROL BOARD.
        /// </summary>
        public static string title_Dashboard {
            get {
                return ResourceManager.GetString("title_Dashboard", resourceCulture);
            }
        }
    }
}
