//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MFG {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemoldDefects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoldDefects() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MFG.DemoldDefects", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Scheduled Families.
        /// </summary>
        internal static string btn_ShowScheduledFamilies {
            get {
                return ResourceManager.GetString("btn_ShowScheduledFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adition.
        /// </summary>
        internal static string lbl_Adition {
            get {
                return ResourceManager.GetString("lbl_Adition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adition Category.
        /// </summary>
        internal static string lbl_AditionCategory {
            get {
                return ResourceManager.GetString("lbl_AditionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The chosen product is in the system but is not in production, do you want to add a defect even so?.
        /// </summary>
        internal static string lbl_AlertMessageText {
            get {
                return ResourceManager.GetString("lbl_AlertMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert.
        /// </summary>
        internal static string lbl_AlertMessageTitle {
            get {
                return ResourceManager.GetString("lbl_AlertMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base.
        /// </summary>
        internal static string lbl_Base {
            get {
                return ResourceManager.GetString("lbl_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base Category.
        /// </summary>
        internal static string lbl_BaseCategory {
            get {
                return ResourceManager.GetString("lbl_BaseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check this if you prefer to enter the amount.
        /// </summary>
        internal static string lbl_CheckThisManualAmount {
            get {
                return ResourceManager.GetString("lbl_CheckThisManualAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Defect.
        /// </summary>
        internal static string lbl_Defect {
            get {
                return ResourceManager.GetString("lbl_Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Defect Type.
        /// </summary>
        internal static string lbl_DefectType {
            get {
                return ResourceManager.GetString("lbl_DefectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demold Defects.
        /// </summary>
        internal static string lbl_DemoldDefects {
            get {
                return ResourceManager.GetString("lbl_DemoldDefects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Design.
        /// </summary>
        internal static string lbl_Design {
            get {
                return ResourceManager.GetString("lbl_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family.
        /// </summary>
        internal static string lbl_Family {
            get {
                return ResourceManager.GetString("lbl_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inspector.
        /// </summary>
        internal static string lbl_Inspector {
            get {
                return ResourceManager.GetString("lbl_Inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lens Type Production.
        /// </summary>
        internal static string lbl_LensTypeProdQty {
            get {
                return ResourceManager.GetString("lbl_LensTypeProdQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Len Type.
        /// </summary>
        internal static string lbl_LenType {
            get {
                return ResourceManager.GetString("lbl_LenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (No Additions).
        /// </summary>
        internal static string lbl_NoAddition {
            get {
                return ResourceManager.GetString("lbl_NoAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planning Qty.
        /// </summary>
        internal static string lbl_PlanningQty {
            get {
                return ResourceManager.GetString("lbl_PlanningQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Production Process.
        /// </summary>
        internal static string lbl_ProductionProcess {
            get {
                return ResourceManager.GetString("lbl_ProductionProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        internal static string lbl_Quantity {
            get {
                return ResourceManager.GetString("lbl_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Side.
        /// </summary>
        internal static string lbl_Side {
            get {
                return ResourceManager.GetString("lbl_Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Put the amount here.
        /// </summary>
        internal static string lbl_TextboxDefectQty {
            get {
                return ResourceManager.GetString("lbl_TextboxDefectQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no product with the chosen combination, try another..
        /// </summary>
        internal static string msg_CombinationProductNotExists {
            get {
                return ResourceManager.GetString("msg_CombinationProductNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please choose a defect.
        /// </summary>
        internal static string msg_DefectRequired {
            get {
                return ResourceManager.GetString("msg_DefectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This VAT has no products in Production, you can press &quot;Show All&quot; to see all products.
        /// </summary>
        internal static string msg_ProductionFamilyNothing {
            get {
                return ResourceManager.GetString("msg_ProductionFamilyNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This VAT number has the product {0} in production but is not in the catalog.
        /// </summary>
        internal static string msg_ProductionFamilyNotInCatalog {
            get {
                return ResourceManager.GetString("msg_ProductionFamilyNotInCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fill in all fields to continue.
        /// </summary>
        internal static string msg_SelectAllFields {
            get {
                return ResourceManager.GetString("msg_SelectAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login or register of User.
        /// </summary>
        internal static string title_LoginRegister {
            get {
                return ResourceManager.GetString("title_LoginRegister", resourceCulture);
            }
        }
    }
}
