//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MFG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MoldFamilies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MoldFamilies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MFG.MoldFamilies", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update From Excel.
        /// </summary>
        internal static string btn_UpdateFromExcel {
            get {
                return ResourceManager.GetString("btn_UpdateFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        internal static string lbl_FamilyName {
            get {
                return ResourceManager.GetString("lbl_FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens.
        /// </summary>
        internal static string lbl_Lens {
            get {
                return ResourceManager.GetString("lbl_Lens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LensTypes.
        /// </summary>
        internal static string lbl_LensTypes {
            get {
                return ResourceManager.GetString("lbl_LensTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Len Types.
        /// </summary>
        internal static string lbl_LenTypes {
            get {
                return ResourceManager.GetString("lbl_LenTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are sure you want to delete the len type?.
        /// </summary>
        internal static string msg_DeleteLenTypeRecordConfirm {
            get {
                return ResourceManager.GetString("msg_DeleteLenTypeRecordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are sure you want to delete the mold family?.
        /// </summary>
        internal static string msg_DeleteMoldFamilyRecordConfirm {
            get {
                return ResourceManager.GetString("msg_DeleteMoldFamilyRecordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information has been updated.
        /// </summary>
        internal static string msg_ExcelImportMessage {
            get {
                return ResourceManager.GetString("msg_ExcelImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of lens is already assigned.
        /// </summary>
        internal static string msg_LenTypeAlreadyAssigned {
            get {
                return ResourceManager.GetString("msg_LenTypeAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this record, the family must have at least one type of lens..
        /// </summary>
        internal static string msg_LenTypesRequiredInTable {
            get {
                return ResourceManager.GetString("msg_LenTypesRequiredInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mold family was deleted successfully.
        /// </summary>
        internal static string msg_MoldFamilyDeleted {
            get {
                return ResourceManager.GetString("msg_MoldFamilyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a lens type.
        /// </summary>
        internal static string msg_SelectLensType {
            get {
                return ResourceManager.GetString("msg_SelectLensType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mold Families List.
        /// </summary>
        internal static string title_MoldFamiliesList {
            get {
                return ResourceManager.GetString("title_MoldFamiliesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mold Family.
        /// </summary>
        internal static string title_NewMoldFamily {
            get {
                return ResourceManager.GetString("title_NewMoldFamily", resourceCulture);
            }
        }
    }
}
