//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MFG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MFG.Reports", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendant.
        /// </summary>
        internal static string lbl_Attendant {
            get {
                return ResourceManager.GetString("lbl_Attendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cavities.
        /// </summary>
        internal static string lbl_Cavities {
            get {
                return ResourceManager.GetString("lbl_Cavities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date type.
        /// </summary>
        internal static string lbl_DateType {
            get {
                return ResourceManager.GetString("lbl_DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date time.
        /// </summary>
        internal static string lbl_EndDatetime {
            get {
                return ResourceManager.GetString("lbl_EndDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string lbl_Export {
            get {
                return ResourceManager.GetString("lbl_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaskets.
        /// </summary>
        internal static string lbl_Gaskets {
            get {
                return ResourceManager.GetString("lbl_Gaskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within specification?.
        /// </summary>
        internal static string lbl_IsGood {
            get {
                return ResourceManager.GetString("lbl_IsGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines.
        /// </summary>
        internal static string lbl_Machines {
            get {
                return ResourceManager.GetString("lbl_Machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        internal static string lbl_Materials {
            get {
                return ResourceManager.GetString("lbl_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string lbl_Parameters {
            get {
                return ResourceManager.GetString("lbl_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters for.
        /// </summary>
        internal static string lbl_ParametersFor {
            get {
                return ResourceManager.GetString("lbl_ParametersFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string lbl_Process {
            get {
                return ResourceManager.GetString("lbl_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions Reports.
        /// </summary>
        internal static string lbl_Report_ACT {
            get {
                return ResourceManager.GetString("lbl_Report_ACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EER Details Report.
        /// </summary>
        internal static string lbl_Report_EERDTLS {
            get {
                return ResourceManager.GetString("lbl_Report_EERDTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Gasket Diameter.
        /// </summary>
        internal static string lbl_Report_GSKTDIAM {
            get {
                return ResourceManager.GetString("lbl_Report_GSKTDIAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters Report.
        /// </summary>
        internal static string lbl_Report_PRMS {
            get {
                return ResourceManager.GetString("lbl_Report_PRMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibles.
        /// </summary>
        internal static string lbl_Responsibles {
            get {
                return ResourceManager.GetString("lbl_Responsibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setups.
        /// </summary>
        internal static string lbl_Setups {
            get {
                return ResourceManager.GetString("lbl_Setups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts.
        /// </summary>
        internal static string lbl_Shifts {
            get {
                return ResourceManager.GetString("lbl_Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date time.
        /// </summary>
        internal static string lbl_StartDatetime {
            get {
                return ResourceManager.GetString("lbl_StartDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lbl_Status {
            get {
                return ResourceManager.GetString("lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string title_Reports {
            get {
                return ResourceManager.GetString("title_Reports", resourceCulture);
            }
        }
    }
}
