//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MNT {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnergySensors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnergySensors() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MNT.EnergySensors", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Sensor.
        /// </summary>
        internal static string btn_NewSensor {
            get {
                return ResourceManager.GetString("btn_NewSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alarms.
        /// </summary>
        internal static string lbl_Alarms {
            get {
                return ResourceManager.GetString("lbl_Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumption.
        /// </summary>
        internal static string lbl_Consumption {
            get {
                return ResourceManager.GetString("lbl_Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy config from.
        /// </summary>
        internal static string lbl_CopyConfigFrom {
            get {
                return ResourceManager.GetString("lbl_CopyConfigFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy Energy Sensor.
        /// </summary>
        internal static string lbl_CopyEnergySensor {
            get {
                return ResourceManager.GetString("lbl_CopyEnergySensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device Id.
        /// </summary>
        internal static string lbl_DeviceId {
            get {
                return ResourceManager.GetString("lbl_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Family Sensor.
        /// </summary>
        internal static string lbl_EditFamilySensor {
            get {
                return ResourceManager.GetString("lbl_EditFamilySensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Families.
        /// </summary>
        internal static string lbl_Families {
            get {
                return ResourceManager.GetString("lbl_Families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family.
        /// </summary>
        internal static string lbl_Family {
            get {
                return ResourceManager.GetString("lbl_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family Name.
        /// </summary>
        internal static string lbl_FamilyName {
            get {
                return ResourceManager.GetString("lbl_FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General Information.
        /// </summary>
        internal static string lbl_GeneralInformation {
            get {
                return ResourceManager.GetString("lbl_GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Global Consumption By.
        /// </summary>
        internal static string lbl_GlobalConsumptionBy {
            get {
                return ResourceManager.GetString("lbl_GlobalConsumptionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hour.
        /// </summary>
        internal static string lbl_Hour {
            get {
                return ResourceManager.GetString("lbl_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        internal static string lbl_Image {
            get {
                return ResourceManager.GetString("lbl_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Index Key.
        /// </summary>
        internal static string lbl_IndexKey {
            get {
                return ResourceManager.GetString("lbl_IndexKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Hour.
        /// </summary>
        internal static string lbl_LastHour {
            get {
                return ResourceManager.GetString("lbl_LastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max Value.
        /// </summary>
        internal static string lbl_MaxValue {
            get {
                return ResourceManager.GetString("lbl_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Maximo Por Hora.
        /// </summary>
        internal static string lbl_MaxValuePerHour {
            get {
                return ResourceManager.GetString("lbl_MaxValuePerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New name for copied sensor.
        /// </summary>
        internal static string lbl_NameForCopy {
            get {
                return ResourceManager.GetString("lbl_NameForCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Family.
        /// </summary>
        internal static string lbl_NewFamily {
            get {
                return ResourceManager.GetString("lbl_NewFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Family Sensor.
        /// </summary>
        internal static string lbl_NewFamilySensor {
            get {
                return ResourceManager.GetString("lbl_NewFamilySensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Name.
        /// </summary>
        internal static string lbl_NewName {
            get {
                return ResourceManager.GetString("lbl_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Use.
        /// </summary>
        internal static string lbl_NewUse {
            get {
                return ResourceManager.GetString("lbl_NewUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Period Consumption by Day.
        /// </summary>
        internal static string lbl_PeriodConsumptionByDay {
            get {
                return ResourceManager.GetString("lbl_PeriodConsumptionByDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Family.
        /// </summary>
        internal static string lbl_SelectFamily {
            get {
                return ResourceManager.GetString("lbl_SelectFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Name.
        /// </summary>
        internal static string lbl_SelectName {
            get {
                return ResourceManager.GetString("lbl_SelectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Sensor.
        /// </summary>
        internal static string lbl_SelectSensor {
            get {
                return ResourceManager.GetString("lbl_SelectSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Unit.
        /// </summary>
        internal static string lbl_SelectUnit {
            get {
                return ResourceManager.GetString("lbl_SelectUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Use.
        /// </summary>
        internal static string lbl_SelectUse {
            get {
                return ResourceManager.GetString("lbl_SelectUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor.
        /// </summary>
        internal static string lbl_Sensor {
            get {
                return ResourceManager.GetString("lbl_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor Name.
        /// </summary>
        internal static string lbl_SensorName {
            get {
                return ResourceManager.GetString("lbl_SensorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set.
        /// </summary>
        internal static string lbl_Set {
            get {
                return ResourceManager.GetString("lbl_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set Same Value.
        /// </summary>
        internal static string lbl_SetSameValue {
            get {
                return ResourceManager.GetString("lbl_SetSameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Energy Sensors.
        /// </summary>
        internal static string lbl_Title {
            get {
                return ResourceManager.GetString("lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unit.
        /// </summary>
        internal static string lbl_Unit {
            get {
                return ResourceManager.GetString("lbl_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload.
        /// </summary>
        internal static string lbl_Upload {
            get {
                return ResourceManager.GetString("lbl_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload Image.
        /// </summary>
        internal static string lbl_UploadImage {
            get {
                return ResourceManager.GetString("lbl_UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use.
        /// </summary>
        internal static string lbl_Use {
            get {
                return ResourceManager.GetString("lbl_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the family?.
        /// </summary>
        internal static string msg_ConfirmDeleteFamily {
            get {
                return ResourceManager.GetString("msg_ConfirmDeleteFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the sensor?.
        /// </summary>
        internal static string msg_DeleteConfirmationEnergySensor {
            get {
                return ResourceManager.GetString("msg_DeleteConfirmationEnergySensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The family was successfully updated.
        /// </summary>
        internal static string msg_EditedFamilySaved {
            get {
                return ResourceManager.GetString("msg_EditedFamilySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family Already Exist.
        /// </summary>
        internal static string msg_FamilyAlreadyExist {
            get {
                return ResourceManager.GetString("msg_FamilyAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The family was deleted..
        /// </summary>
        internal static string msg_FamilyDeleted {
            get {
                return ResourceManager.GetString("msg_FamilyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new family was succesfully added.
        /// </summary>
        internal static string msg_NewFamilyAdded {
            get {
                return ResourceManager.GetString("msg_NewFamilyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot save empty fields.
        /// </summary>
        internal static string msg_NonEmptyFieldsRequired {
            get {
                return ResourceManager.GetString("msg_NonEmptyFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Name and the Max Value are required fields.
        /// </summary>
        internal static string msg_RequiredNameMaxValue {
            get {
                return ResourceManager.GetString("msg_RequiredNameMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The sensor was successfully added.
        /// </summary>
        internal static string msg_SensorAdded {
            get {
                return ResourceManager.GetString("msg_SensorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The sensor was successfully copied.
        /// </summary>
        internal static string msg_SensorCopied {
            get {
                return ResourceManager.GetString("msg_SensorCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The sensor was successfully deleted.
        /// </summary>
        internal static string msg_SensorDeleted {
            get {
                return ResourceManager.GetString("msg_SensorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The sensor was successfully updated.
        /// </summary>
        internal static string msg_SensorUpdated {
            get {
                return ResourceManager.GetString("msg_SensorUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to load the values ​​of the selected sensor to those of this alarm?.
        /// </summary>
        internal static string msg_SetConfigurationValuesForAlarm {
            get {
                return ResourceManager.GetString("msg_SetConfigurationValuesForAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a valid option.
        /// </summary>
        internal static string msg_ValueOptionRequired {
            get {
                return ResourceManager.GetString("msg_ValueOptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alarms Configuration.
        /// </summary>
        internal static string title_AlarmsConfiguration {
            get {
                return ResourceManager.GetString("title_AlarmsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Energy Consumption By.
        /// </summary>
        internal static string title_EnergyConsumtionBy {
            get {
                return ResourceManager.GetString("title_EnergyConsumtionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Energy Consumption Dashboard.
        /// </summary>
        internal static string title_EnergyConsumtionDashboard {
            get {
                return ResourceManager.GetString("title_EnergyConsumtionDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Energy Family Sensors.
        /// </summary>
        internal static string title_EnergyFamilySensors {
            get {
                return ResourceManager.GetString("title_EnergyFamilySensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert Report.
        /// </summary>
        internal static string title_ExcelReportAlert {
            get {
                return ResourceManager.GetString("title_ExcelReportAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consumption.
        /// </summary>
        internal static string title_FamilyConsumption {
            get {
                return ResourceManager.GetString("title_FamilyConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensor Edit.
        /// </summary>
        internal static string title_SensorEdit {
            get {
                return ResourceManager.GetString("title_SensorEdit", resourceCulture);
            }
        }
    }
}
