//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Request {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Request() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Request", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the material to be returned.
        /// </summary>
        internal static string alert_ReturnMaterialInstruction {
            get {
                return ResourceManager.GetString("alert_ReturnMaterialInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string btn_Approve {
            get {
                return ResourceManager.GetString("btn_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save signature.
        /// </summary>
        internal static string btn_CreateSignature {
            get {
                return ResourceManager.GetString("btn_CreateSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit my signature.
        /// </summary>
        internal static string btn_EditSignature {
            get {
                return ResourceManager.GetString("btn_EditSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string btn_Reject {
            get {
                return ResourceManager.GetString("btn_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btn_Reset {
            get {
                return ResourceManager.GetString("btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Loan.
        /// </summary>
        internal static string btn_ReturnLoan {
            get {
                return ResourceManager.GetString("btn_ReturnLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow attachments.
        /// </summary>
        internal static string H_AllowAttachments {
            get {
                return ResourceManager.GetString("H_AllowAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        internal static string H_CreateRequest {
            get {
                return ResourceManager.GetString("H_CreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Requisition.
        /// </summary>
        internal static string H_eRequest {
            get {
                return ResourceManager.GetString("H_eRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string H_Format {
            get {
                return ResourceManager.GetString("H_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string H_FormatName {
            get {
                return ResourceManager.GetString("H_FormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats.
        /// </summary>
        internal static string H_Formats {
            get {
                return ResourceManager.GetString("H_Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string H_IsEnabled {
            get {
                return ResourceManager.GetString("H_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use detail.
        /// </summary>
        internal static string H_ManageDetail {
            get {
                return ResourceManager.GetString("H_ManageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the details to show.
        /// </summary>
        internal static string H_SelectDetailsShow {
            get {
                return ResourceManager.GetString("H_SelectDetailsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use doble verification.
        /// </summary>
        internal static string H_Use2FA {
            get {
                return ResourceManager.GetString("H_Use2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use direct approval.
        /// </summary>
        internal static string H_UseDirectApproval {
            get {
                return ResourceManager.GetString("H_UseDirectApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Part.
        /// </summary>
        internal static string lblDatePart {
            get {
                return ResourceManager.GetString("lblDatePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        internal static string lblExceptions {
            get {
                return ResourceManager.GetString("lblExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use double verification.
        /// </summary>
        internal static string lbl_2FA {
            get {
                return ResourceManager.GetString("lbl_2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the format.
        /// </summary>
        internal static string lbl_AccessFormat {
            get {
                return ResourceManager.GetString("lbl_AccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access granted to.
        /// </summary>
        internal static string lbl_AccessGarantedTo {
            get {
                return ResourceManager.GetString("lbl_AccessGarantedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add condition.
        /// </summary>
        internal static string lbl_AddCondition {
            get {
                return ResourceManager.GetString("lbl_AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Depurty.
        /// </summary>
        internal static string lbl_AddDepurty {
            get {
                return ResourceManager.GetString("lbl_AddDepurty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add detail field.
        /// </summary>
        internal static string lbl_AddDetailField {
            get {
                return ResourceManager.GetString("lbl_AddDetailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add exception.
        /// </summary>
        internal static string lbl_AddException {
            get {
                return ResourceManager.GetString("lbl_AddException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file.
        /// </summary>
        internal static string lbl_AddFile {
            get {
                return ResourceManager.GetString("lbl_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add format fields.
        /// </summary>
        internal static string lbl_AddFormatFields {
            get {
                return ResourceManager.GetString("lbl_AddFormatFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Access Format.
        /// </summary>
        internal static string lbl_AddNewAccessFormat {
            get {
                return ResourceManager.GetString("lbl_AddNewAccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new approver.
        /// </summary>
        internal static string lbl_AddNewApprover {
            get {
                return ResourceManager.GetString("lbl_AddNewApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Phase.
        /// </summary>
        internal static string lbl_AddPhase {
            get {
                return ResourceManager.GetString("lbl_AddPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rule.
        /// </summary>
        internal static string lbl_AddRule {
            get {
                return ResourceManager.GetString("lbl_AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All departments.
        /// </summary>
        internal static string lbl_AllDepartments {
            get {
                return ResourceManager.GetString("lbl_AllDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Facilities.
        /// </summary>
        internal static string lbl_AllFacility {
            get {
                return ResourceManager.GetString("lbl_AllFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow attachments.
        /// </summary>
        internal static string lbl_AllowAttachments {
            get {
                return ResourceManager.GetString("lbl_AllowAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        internal static string lbl_AllUsers {
            get {
                return ResourceManager.GetString("lbl_AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string lbl_Approval {
            get {
                return ResourceManager.GetString("lbl_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval phases.
        /// </summary>
        internal static string lbl_ApprovalPhases {
            get {
                return ResourceManager.GetString("lbl_ApprovalPhases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvals.
        /// </summary>
        internal static string lbl_Approvals {
            get {
                return ResourceManager.GetString("lbl_Approvals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string lbl_Approve {
            get {
                return ResourceManager.GetString("lbl_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        internal static string lbl_Approver {
            get {
                return ResourceManager.GetString("lbl_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string lbl_ApprovingDepartment {
            get {
                return ResourceManager.GetString("lbl_ApprovingDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approving user.
        /// </summary>
        internal static string lbl_ApprovingUser {
            get {
                return ResourceManager.GetString("lbl_ApprovingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string lbl_Article {
            get {
                return ResourceManager.GetString("lbl_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string lbl_Articles {
            get {
                return ResourceManager.GetString("lbl_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string lbl_Attachments {
            get {
                return ResourceManager.GetString("lbl_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Request.
        /// </summary>
        internal static string lbl_CancelRequest {
            get {
                return ResourceManager.GetString("lbl_CancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog List.
        /// </summary>
        internal static string lbl_CatalogList {
            get {
                return ResourceManager.GetString("lbl_CatalogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change file.
        /// </summary>
        internal static string lbl_ChangeFile {
            get {
                return ResourceManager.GetString("lbl_ChangeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string lbl_Code {
            get {
                return ResourceManager.GetString("lbl_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string lbl_Comments {
            get {
                return ResourceManager.GetString("lbl_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string lbl_Company {
            get {
                return ResourceManager.GetString("lbl_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept.
        /// </summary>
        internal static string lbl_Concept {
            get {
                return ResourceManager.GetString("lbl_Concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string lbl_CreatedBy {
            get {
                return ResourceManager.GetString("lbl_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create rule.
        /// </summary>
        internal static string lbl_CreateRule {
            get {
                return ResourceManager.GetString("lbl_CreateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimals.
        /// </summary>
        internal static string lbl_Decimals {
            get {
                return ResourceManager.GetString("lbl_Decimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete rule.
        /// </summary>
        internal static string lbl_DeleteRule {
            get {
                return ResourceManager.GetString("lbl_DeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string lbl_Department {
            get {
                return ResourceManager.GetString("lbl_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string lbl_Detail {
            get {
                return ResourceManager.GetString("lbl_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail fields.
        /// </summary>
        internal static string lbl_DetailFields {
            get {
                return ResourceManager.GetString("lbl_DetailFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send for direct approval.
        /// </summary>
        internal static string lbl_DirectApproval {
            get {
                return ResourceManager.GetString("lbl_DirectApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit approver.
        /// </summary>
        internal static string lbl_EditApprover {
            get {
                return ResourceManager.GetString("lbl_EditApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit detail field.
        /// </summary>
        internal static string lbl_EditDetailField {
            get {
                return ResourceManager.GetString("lbl_EditDetailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit folio.
        /// </summary>
        internal static string lbl_EditFolio {
            get {
                return ResourceManager.GetString("lbl_EditFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Format.
        /// </summary>
        internal static string lbl_EditFormat {
            get {
                return ResourceManager.GetString("lbl_EditFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rule.
        /// </summary>
        internal static string lbl_EditRule {
            get {
                return ResourceManager.GetString("lbl_EditRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Signature.
        /// </summary>
        internal static string lbl_ElectronicSignature {
            get {
                return ResourceManager.GetString("lbl_ElectronicSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End field.
        /// </summary>
        internal static string lbl_EndField {
            get {
                return ResourceManager.GetString("lbl_EndField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End number.
        /// </summary>
        internal static string lbl_EndNumber {
            get {
                return ResourceManager.GetString("lbl_EndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string lbl_Field {
            get {
                return ResourceManager.GetString("lbl_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flows.
        /// </summary>
        internal static string lbl_Flows {
            get {
                return ResourceManager.GetString("lbl_Flows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        internal static string lbl_Folio {
            get {
                return ResourceManager.GetString("lbl_Folio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string lbl_Font {
            get {
                return ResourceManager.GetString("lbl_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font color.
        /// </summary>
        internal static string lbl_FontColor {
            get {
                return ResourceManager.GetString("lbl_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string lbl_FontSize {
            get {
                return ResourceManager.GetString("lbl_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format field.
        /// </summary>
        internal static string lbl_FormatField {
            get {
                return ResourceManager.GetString("lbl_FormatField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format fields.
        /// </summary>
        internal static string lbl_FormatFields {
            get {
                return ResourceManager.GetString("lbl_FormatFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format name.
        /// </summary>
        internal static string lbl_FormatName {
            get {
                return ResourceManager.GetString("lbl_FormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string lbl_Forward {
            get {
                return ResourceManager.GetString("lbl_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        internal static string lbl_General {
            get {
                return ResourceManager.GetString("lbl_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Approval Log.
        /// </summary>
        internal static string lbl_HideApprovalLog {
            get {
                return ResourceManager.GetString("lbl_HideApprovalLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Attachments.
        /// </summary>
        internal static string lbl_HideAttachments {
            get {
                return ResourceManager.GetString("lbl_HideAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Detail.
        /// </summary>
        internal static string lbl_HideDetail {
            get {
                return ResourceManager.GetString("lbl_HideDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal position.
        /// </summary>
        internal static string lbl_HorizontalPosition {
            get {
                return ResourceManager.GetString("lbl_HorizontalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image height.
        /// </summary>
        internal static string lbl_ImageHeight {
            get {
                return ResourceManager.GetString("lbl_ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image width.
        /// </summary>
        internal static string lbl_ImageWidth {
            get {
                return ResourceManager.GetString("lbl_ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial horizontal position.
        /// </summary>
        internal static string lbl_InitialHorizontalPosition {
            get {
                return ResourceManager.GetString("lbl_InitialHorizontalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string lbl_Invoice {
            get {
                return ResourceManager.GetString("lbl_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is enabled?.
        /// </summary>
        internal static string lbl_IsEnabled {
            get {
                return ResourceManager.GetString("lbl_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        internal static string lbl_IsEquals {
            get {
                return ResourceManager.GetString("lbl_IsEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justification.
        /// </summary>
        internal static string lbl_Justification {
            get {
                return ResourceManager.GetString("lbl_Justification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languague.
        /// </summary>
        internal static string lbl_Languague {
            get {
                return ResourceManager.GetString("lbl_Languague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string lbl_Length {
            get {
                return ResourceManager.GetString("lbl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line spacing.
        /// </summary>
        internal static string lbl_LineSpacing {
            get {
                return ResourceManager.GetString("lbl_LineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is listed?.
        /// </summary>
        internal static string lbl_Listed {
            get {
                return ResourceManager.GetString("lbl_Listed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListName.
        /// </summary>
        internal static string lbl_ListName {
            get {
                return ResourceManager.GetString("lbl_ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage detail.
        /// </summary>
        internal static string lbl_ManageDetail {
            get {
                return ResourceManager.GetString("lbl_ManageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Mandatory?.
        /// </summary>
        internal static string lbl_Mandatory {
            get {
                return ResourceManager.GetString("lbl_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of details.
        /// </summary>
        internal static string lbl_MaximumNumberDetails {
            get {
                return ResourceManager.GetString("lbl_MaximumNumberDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string lbl_Model {
            get {
                return ResourceManager.GetString("lbl_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New condition.
        /// </summary>
        internal static string lbl_NewCondition {
            get {
                return ResourceManager.GetString("lbl_NewCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New exception.
        /// </summary>
        internal static string lbl_NewException {
            get {
                return ResourceManager.GetString("lbl_NewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New rule.
        /// </summary>
        internal static string lbl_NewRule {
            get {
                return ResourceManager.GetString("lbl_NewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Selected.
        /// </summary>
        internal static string lbl_NothingSelected {
            get {
                return ResourceManager.GetString("lbl_NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string lbl_Number {
            get {
                return ResourceManager.GetString("lbl_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output type.
        /// </summary>
        internal static string lbl_OutputType {
            get {
                return ResourceManager.GetString("lbl_OutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material owned by.
        /// </summary>
        internal static string lbl_Owned {
            get {
                return ResourceManager.GetString("lbl_Owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        internal static string lbl_Phase {
            get {
                return ResourceManager.GetString("lbl_Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate number.
        /// </summary>
        internal static string lbl_PlateNumber {
            get {
                return ResourceManager.GetString("lbl_PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string lbl_Position {
            get {
                return ResourceManager.GetString("lbl_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precition.
        /// </summary>
        internal static string lbl_Precition {
            get {
                return ResourceManager.GetString("lbl_Precition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Format.
        /// </summary>
        internal static string lbl_PrintFormat {
            get {
                return ResourceManager.GetString("lbl_PrintFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string lbl_Request {
            get {
                return ResourceManager.GetString("lbl_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested fields.
        /// </summary>
        internal static string lbl_RequestedFields {
            get {
                return ResourceManager.GetString("lbl_RequestedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement number.
        /// </summary>
        internal static string lbl_RequirementNumber {
            get {
                return ResourceManager.GetString("lbl_RequirementNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return By.
        /// </summary>
        internal static string lbl_ReturnBy {
            get {
                return ResourceManager.GetString("lbl_ReturnBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date.
        /// </summary>
        internal static string lbl_ReturnDate {
            get {
                return ResourceManager.GetString("lbl_ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        internal static string lbl_Rule {
            get {
                return ResourceManager.GetString("lbl_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule configuration.
        /// </summary>
        internal static string lbl_RuleConfiguration {
            get {
                return ResourceManager.GetString("lbl_RuleConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string lbl_Rules {
            get {
                return ResourceManager.GetString("lbl_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Approval Log.
        /// </summary>
        internal static string lbl_SeeApprovalLog {
            get {
                return ResourceManager.GetString("lbl_SeeApprovalLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        internal static string lbl_SerialNumber {
            get {
                return ResourceManager.GetString("lbl_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up PDF document.
        /// </summary>
        internal static string lbl_SetUpPDF {
            get {
                return ResourceManager.GetString("lbl_SetUpPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show as.
        /// </summary>
        internal static string lbl_ShowAs {
            get {
                return ResourceManager.GetString("lbl_ShowAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show when.
        /// </summary>
        internal static string lbl_ShowWhen {
            get {
                return ResourceManager.GetString("lbl_ShowWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string lbl_signature {
            get {
                return ResourceManager.GetString("lbl_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature configuration.
        /// </summary>
        internal static string lbl_SignatureConfiguration {
            get {
                return ResourceManager.GetString("lbl_SignatureConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start field.
        /// </summary>
        internal static string lbl_StartField {
            get {
                return ResourceManager.GetString("lbl_StartField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start number.
        /// </summary>
        internal static string lbl_StartNumber {
            get {
                return ResourceManager.GetString("lbl_StartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lbl_Status {
            get {
                return ResourceManager.GetString("lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance.
        /// </summary>
        internal static string lbl_Tolerance {
            get {
                return ResourceManager.GetString("lbl_Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lbl_Type {
            get {
                return ResourceManager.GetString("lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use two-factor authentication.
        /// </summary>
        internal static string lbl_Use2FA {
            get {
                return ResourceManager.GetString("lbl_Use2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use direct approval.
        /// </summary>
        internal static string lbl_UseDirectApproval {
            get {
                return ResourceManager.GetString("lbl_UseDirectApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Access.
        /// </summary>
        internal static string lbl_UserAccess {
            get {
                return ResourceManager.GetString("lbl_UserAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username and password.
        /// </summary>
        internal static string lbl_UserPassMandatory {
            get {
                return ResourceManager.GetString("lbl_UserPassMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User validated successfully.
        /// </summary>
        internal static string lbl_ValidatedUserSuccess {
            get {
                return ResourceManager.GetString("lbl_ValidatedUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User credentials are incorrect.
        /// </summary>
        internal static string lbl_ValidatedUserWrong {
            get {
                return ResourceManager.GetString("lbl_ValidatedUserWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string lbl_Value {
            get {
                return ResourceManager.GetString("lbl_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to show.
        /// </summary>
        internal static string lbl_ValueToShow {
            get {
                return ResourceManager.GetString("lbl_ValueToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical position.
        /// </summary>
        internal static string lbl_VerticalPosition {
            get {
                return ResourceManager.GetString("lbl_VerticalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Attachments.
        /// </summary>
        internal static string lbl_ViewAttachments {
            get {
                return ResourceManager.GetString("lbl_ViewAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Detail.
        /// </summary>
        internal static string lbl_ViewDetail {
            get {
                return ResourceManager.GetString("lbl_ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is visible?.
        /// </summary>
        internal static string lbl_Visible {
            get {
                return ResourceManager.GetString("lbl_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        internal static string lbl_WithDecimals {
            get {
                return ResourceManager.GetString("lbl_WithDecimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can approve after.
        /// </summary>
        internal static string lbl_YouCanApproveAfter {
            get {
                return ResourceManager.GetString("lbl_YouCanApproveAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the creation, if you cancel all edited here they will be lost?.
        /// </summary>
        internal static string msg_CancelFormatCreate {
            get {
                return ResourceManager.GetString("msg_CancelFormatCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to return to the list of requirements? All changes made will be lost..
        /// </summary>
        internal static string msg_CancelReqCreate {
            get {
                return ResourceManager.GetString("msg_CancelReqCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the request?.
        /// </summary>
        internal static string msg_CancelRequest {
            get {
                return ResourceManager.GetString("msg_CancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new access code will be generated, the previous one will no longer work.
        /// </summary>
        internal static string msg_CreateNewApproval2FA {
            get {
                return ResourceManager.GetString("msg_CreateNewApproval2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create this requirement?.
        /// </summary>
        internal static string msg_CreateReqConfirmation {
            get {
                return ResourceManager.GetString("msg_CreateReqConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        internal static string msg_Delete_Confirm {
            get {
                return ResourceManager.GetString("msg_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length cannot be 0.
        /// </summary>
        internal static string msg_ErrorLength {
            get {
                return ResourceManager.GetString("msg_ErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision cannot be 0.
        /// </summary>
        internal static string msg_ErrorPrecision {
            get {
                return ResourceManager.GetString("msg_ErrorPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a plant and a format..
        /// </summary>
        internal static string msg_FacilityFormatMandatory {
            get {
                return ResourceManager.GetString("msg_FacilityFormatMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the format is from the department of:.
        /// </summary>
        internal static string msg_IfTheFormatIs {
            get {
                return ResourceManager.GetString("msg_IfTheFormatIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you are trying to approve is not a valid user to approve this phase, do you want to authenticate to approve the phase?.
        /// </summary>
        internal static string msg_LoginApprove {
            get {
                return ResourceManager.GetString("msg_LoginApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password that came to your email.
        /// </summary>
        internal static string msg_Msg2FA {
            get {
                return ResourceManager.GetString("msg_Msg2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name cannot be empty.
        /// </summary>
        internal static string msg_NameEN {
            get {
                return ResourceManager.GetString("msg_NameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name in Spanish cannot be empty.
        /// </summary>
        internal static string msg_NameES {
            get {
                return ResourceManager.GetString("msg_NameES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then personal approves of:.
        /// </summary>
        internal static string msg_PersonalApproves {
            get {
                return ResourceManager.GetString("msg_PersonalApproves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string msg_SaveChanges {
            get {
                return ResourceManager.GetString("msg_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes made?.
        /// </summary>
        internal static string msg_SaveChangesQ {
            get {
                return ResourceManager.GetString("msg_SaveChangesQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a part of the date to evaluate.
        /// </summary>
        internal static string msg_SelectDatePart {
            get {
                return ResourceManager.GetString("msg_SelectDatePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a field of the format.
        /// </summary>
        internal static string msg_SelectFieldFormat {
            get {
                return ResourceManager.GetString("msg_SelectFieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how you want to configure approval.
        /// </summary>
        internal static string msg_SelectHowYouWant {
            get {
                return ResourceManager.GetString("msg_SelectHowYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have an electronic signature configured, please draw it.
        /// </summary>
        internal static string msg_Signature {
            get {
                return ResourceManager.GetString("msg_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the format field you want to use in this rule..
        /// </summary>
        internal static string msg_step1 {
            get {
                return ResourceManager.GetString("msg_step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate how to compare the field &lt;b&gt;&quot;#FIELD#&quot;&lt;/b&gt;.
        /// </summary>
        internal static string msg_Step2_1 {
            get {
                return ResourceManager.GetString("msg_Step2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Between. If &lt;b&gt;&quot;#FIELD#&quot;&lt;/b&gt; is between 2 values.
        /// </summary>
        internal static string msg_Step2_2 {
            get {
                return ResourceManager.GetString("msg_Step2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + In. If &lt;b&gt;&quot;#FIELD#&quot;&lt;/b&gt; is equal to one of several values.
        /// </summary>
        internal static string msg_Step2_3 {
            get {
                return ResourceManager.GetString("msg_Step2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Like. If &lt;b&gt;&quot;#FIELD#&quot;&lt;/b&gt; is equal to a specific value.
        /// </summary>
        internal static string msg_Step2_4 {
            get {
                return ResourceManager.GetString("msg_Step2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field type cannot use this comparator.
        /// </summary>
        internal static string msg_ThisFieldCanNotUse {
            get {
                return ResourceManager.GetString("msg_ThisFieldCanNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a type.
        /// </summary>
        internal static string msg_TypeMandatory {
            get {
                return ResourceManager.GetString("msg_TypeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval sequence.
        /// </summary>
        internal static string th_ApprovalSequence {
            get {
                return ResourceManager.GetString("th_ApprovalSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the request is from the Department.
        /// </summary>
        internal static string th_IfTheReqFromDepart {
            get {
                return ResourceManager.GetString("th_IfTheReqFromDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New format.
        /// </summary>
        internal static string ttl_NewFormat {
            get {
                return ResourceManager.GetString("ttl_NewFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add approver.
        /// </summary>
        internal static string t_AddApprover {
            get {
                return ResourceManager.GetString("t_AddApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add deputy approver.
        /// </summary>
        internal static string t_AddDeputyApprover {
            get {
                return ResourceManager.GetString("t_AddDeputyApprover", resourceCulture);
            }
        }
    }
}
