//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecurityGuard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityGuard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SG.SecurityGuard", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmo que las siguientes respuestas son verdaderas.
        /// </summary>
        internal static string alert_CovidQuestionnaire {
            get {
                return ResourceManager.GetString("alert_CovidQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar nuevo gafete.
        /// </summary>
        internal static string btn_AddNewBadges {
            get {
                return ResourceManager.GetString("btn_AddNewBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar nueva compañia.
        /// </summary>
        internal static string btn_AddNewCompany {
            get {
                return ResourceManager.GetString("btn_AddNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar nuevo equipo.
        /// </summary>
        internal static string btn_AddNewEquipment {
            get {
                return ResourceManager.GetString("btn_AddNewEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar nuevo guardia.
        /// </summary>
        internal static string btn_AddNewGuard {
            get {
                return ResourceManager.GetString("btn_AddNewGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No usar.
        /// </summary>
        internal static string btn_NotUse {
            get {
                return ResourceManager.GetString("btn_NotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar.
        /// </summary>
        internal static string btn_Use {
            get {
                return ResourceManager.GetString("btn_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string lbl_Active {
            get {
                return ResourceManager.GetString("lbl_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lbl_Add {
            get {
                return ResourceManager.GetString("lbl_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar y nuevo.
        /// </summary>
        internal static string lbl_AddAndNew {
            get {
                return ResourceManager.GetString("lbl_AddAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar compañia.
        /// </summary>
        internal static string lbl_AddCompany {
            get {
                return ResourceManager.GetString("lbl_AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar nuevo empleado.
        /// </summary>
        internal static string lbl_AddNewVendorUser {
            get {
                return ResourceManager.GetString("lbl_AddNewVendorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas disponibles.
        /// </summary>
        internal static string lbl_AvailableTools {
            get {
                return ResourceManager.GetString("lbl_AvailableTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo del gafete.
        /// </summary>
        internal static string lbl_BadgeCode {
            get {
                return ResourceManager.GetString("lbl_BadgeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gafetes.
        /// </summary>
        internal static string lbl_Badges {
            get {
                return ResourceManager.GetString("lbl_Badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de gafete.
        /// </summary>
        internal static string lbl_BadgeType {
            get {
                return ResourceManager.GetString("lbl_BadgeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N. Gafete.
        /// </summary>
        internal static string lbl_BagdeNumber {
            get {
                return ResourceManager.GetString("lbl_BagdeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada.
        /// </summary>
        internal static string lbl_CheckIn {
            get {
                return ResourceManager.GetString("lbl_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida.
        /// </summary>
        internal static string lbl_CheckOut {
            get {
                return ResourceManager.GetString("lbl_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        internal static string lbl_Company {
            get {
                return ResourceManager.GetString("lbl_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuestionario sobre COVID.
        /// </summary>
        internal static string lbl_CovidQuestionnaire {
            get {
                return ResourceManager.GetString("lbl_CovidQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y hora de entrada.
        /// </summary>
        internal static string lbl_DateHourIn {
            get {
                return ResourceManager.GetString("lbl_DateHourIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y hora de salida.
        /// </summary>
        internal static string lbl_DateHourOut {
            get {
                return ResourceManager.GetString("lbl_DateHourOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        internal static string lbl_Department {
            get {
                return ResourceManager.GetString("lbl_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string lbl_Description {
            get {
                return ResourceManager.GetString("lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar proveedor.
        /// </summary>
        internal static string lbl_EditVendorUser {
            get {
                return ResourceManager.GetString("lbl_EditVendorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        internal static string lbl_Employee {
            get {
                return ResourceManager.GetString("lbl_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo.
        /// </summary>
        internal static string lbl_Equipment {
            get {
                return ResourceManager.GetString("lbl_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del equipo.
        /// </summary>
        internal static string lbl_EquipmentName {
            get {
                return ResourceManager.GetString("lbl_EquipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipos.
        /// </summary>
        internal static string lbl_Equipments {
            get {
                return ResourceManager.GetString("lbl_Equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip de equipo.
        /// </summary>
        internal static string lbl_EquipmentType {
            get {
                return ResourceManager.GetString("lbl_EquipmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de expiración.
        /// </summary>
        internal static string lbl_ExpirationDate {
            get {
                return ResourceManager.GetString("lbl_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminar.
        /// </summary>
        internal static string lbl_Finish {
            get {
                return ResourceManager.GetString("lbl_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del guardia.
        /// </summary>
        internal static string lbl_GuardName {
            get {
                return ResourceManager.GetString("lbl_GuardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N. Guardia.
        /// </summary>
        internal static string lbl_GuardNumber {
            get {
                return ResourceManager.GetString("lbl_GuardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardias.
        /// </summary>
        internal static string lbl_Guards {
            get {
                return ResourceManager.GetString("lbl_Guards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto de indetificación.
        /// </summary>
        internal static string lbl_IdentificationPhoto {
            get {
                return ResourceManager.GetString("lbl_IdentificationPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Identificación.
        /// </summary>
        internal static string lbl_IdentificationType {
            get {
                return ResourceManager.GetString("lbl_IdentificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        internal static string lbl_Inactive {
            get {
                return ResourceManager.GetString("lbl_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número del seguro social.
        /// </summary>
        internal static string lbl_InsuranceNumber {
            get {
                return ResourceManager.GetString("lbl_InsuranceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        internal static string lbl_Mark {
            get {
                return ResourceManager.GetString("lbl_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string lbl_Model {
            get {
                return ResourceManager.GetString("lbl_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N. Gafete.
        /// </summary>
        internal static string lbl_NBadge {
            get {
                return ResourceManager.GetString("lbl_NBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo guardia.
        /// </summary>
        internal static string lbl_NewGuard {
            get {
                return ResourceManager.GetString("lbl_NewGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo nombre.
        /// </summary>
        internal static string lbl_NewName {
            get {
                return ResourceManager.GetString("lbl_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N. Serie.
        /// </summary>
        internal static string lbl_NSerie {
            get {
                return ResourceManager.GetString("lbl_NSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propietario.
        /// </summary>
        internal static string lbl_Owner {
            get {
                return ResourceManager.GetString("lbl_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de persona que entra.
        /// </summary>
        internal static string lbl_PersonCheckIngType {
            get {
                return ResourceManager.GetString("lbl_PersonCheckIngType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la persona.
        /// </summary>
        internal static string lbl_PersonName {
            get {
                return ResourceManager.GetString("lbl_PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificación de la persona.
        /// </summary>
        internal static string lbl_PersonVerification {
            get {
                return ResourceManager.GetString("lbl_PersonVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placas.
        /// </summary>
        internal static string lbl_Plates {
            get {
                return ResourceManager.GetString("lbl_Plates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta.
        /// </summary>
        internal static string lbl_PrintLabel {
            get {
                return ResourceManager.GetString("lbl_PrintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo de uso.
        /// </summary>
        internal static string lbl_ReasonForUse {
            get {
                return ResourceManager.GetString("lbl_ReasonForUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        internal static string lbl_Registry {
            get {
                return ResourceManager.GetString("lbl_Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reimprimir etiquetas de acceso.
        /// </summary>
        internal static string lbl_ReprintAccessLabels {
            get {
                return ResourceManager.GetString("lbl_ReprintAccessLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardia responsable.
        /// </summary>
        internal static string lbl_ResponsibleGuard {
            get {
                return ResourceManager.GetString("lbl_ResponsibleGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de acceso.
        /// </summary>
        internal static string lbl_ScannBox {
            get {
                return ResourceManager.GetString("lbl_ScannBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        internal static string lbl_Status {
            get {
                return ResourceManager.GetString("lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        internal static string lbl_Suppliers {
            get {
                return ResourceManager.GetString("lbl_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La herramienta debe llevar una imagen.
        /// </summary>
        internal static string lbl_ToolImgMandatory {
            get {
                return ResourceManager.GetString("lbl_ToolImgMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la herramienta.
        /// </summary>
        internal static string lbl_ToolName {
            get {
                return ResourceManager.GetString("lbl_ToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La herramienta debe de llevar un nombre.
        /// </summary>
        internal static string lbl_ToolNameMandatory {
            get {
                return ResourceManager.GetString("lbl_ToolNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de herramientas.
        /// </summary>
        internal static string lbl_ToolRegister {
            get {
                return ResourceManager.GetString("lbl_ToolRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas.
        /// </summary>
        internal static string lbl_Tools {
            get {
                return ResourceManager.GetString("lbl_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de las herramientas.
        /// </summary>
        internal static string lbl_ToolsData {
            get {
                return ResourceManager.GetString("lbl_ToolsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC.
        /// </summary>
        internal static string lbl_UPC {
            get {
                return ResourceManager.GetString("lbl_UPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir foto nueva.
        /// </summary>
        internal static string lbl_UploadNewPhoto {
            get {
                return ResourceManager.GetString("lbl_UploadNewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso.
        /// </summary>
        internal static string lbl_Use {
            get {
                return ResourceManager.GetString("lbl_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Usa herramientas?.
        /// </summary>
        internal static string lbl_UseTools {
            get {
                return ResourceManager.GetString("lbl_UseTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Usa vehículo?.
        /// </summary>
        internal static string lbl_UseVehicle {
            get {
                return ResourceManager.GetString("lbl_UseVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehículo.
        /// </summary>
        internal static string lbl_Vehicle {
            get {
                return ResourceManager.GetString("lbl_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del vehículo.
        /// </summary>
        internal static string lbl_VehicleData {
            get {
                return ResourceManager.GetString("lbl_VehicleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de verificación.
        /// </summary>
        internal static string lbl_VerificationData {
            get {
                return ResourceManager.GetString("lbl_VerificationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿A quién visita?.
        /// </summary>
        internal static string lbl_WhoVisits {
            get {
                return ResourceManager.GetString("lbl_WhoVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor especificar el nombre de la herramienta y su correspondiente fotografía..
        /// </summary>
        internal static string msg_AddToolInstruction {
            get {
                return ResourceManager.GetString("msg_AddToolInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya tienes un registro de entrada, por favor finalizalo antes de inicar otro..
        /// </summary>
        internal static string msg_CheckInSessionStarted {
            get {
                return ResourceManager.GetString("msg_CheckInSessionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea eliminar al usuario ##USER##?.
        /// </summary>
        internal static string msg_ConfirmDeleteVendorUser {
            get {
                return ResourceManager.GetString("msg_ConfirmDeleteVendorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, parece que no estás en condiciones de acceder a la planta..
        /// </summary>
        internal static string msg_CovidAlertQuestion {
            get {
                return ResourceManager.GetString("msg_CovidAlertQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea eliminar el gafete?.
        /// </summary>
        internal static string msg_DeleteBadgeConfirm {
            get {
                return ResourceManager.GetString("msg_DeleteBadgeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea eliminar la compañia de proveedores?.
        /// </summary>
        internal static string msg_DeleteCompanyConfirm {
            get {
                return ResourceManager.GetString("msg_DeleteCompanyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea borrar el equipo?.
        /// </summary>
        internal static string msg_DeleteEquipmentConfirm {
            get {
                return ResourceManager.GetString("msg_DeleteEquipmentConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo del guardia no existe o no está habilitado para dar permisos..
        /// </summary>
        internal static string msg_DisableMissingGuard {
            get {
                return ResourceManager.GetString("msg_DisableMissingGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo ya ha sido escaneado..
        /// </summary>
        internal static string msg_EquipmentIsScanned {
            get {
                return ResourceManager.GetString("msg_EquipmentIsScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El equipo no ha sido encontrado..
        /// </summary>
        internal static string msg_EquipmentNotFound {
            get {
                return ResourceManager.GetString("msg_EquipmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no accederá con el equipo esta vez, ¿Es correcto?.
        /// </summary>
        internal static string msg_EquipmentRowDeleteConfirm {
            get {
                return ResourceManager.GetString("msg_EquipmentRowDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de expiración para el curso de seguridad de esta persona ha caducado..
        /// </summary>
        internal static string msg_ExpirationDate {
            get {
                return ResourceManager.GetString("msg_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea volver al menú de inicio?.
        /// </summary>
        internal static string msg_HomeLinkConfirmation {
            get {
                return ResourceManager.GetString("msg_HomeLinkConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor identifiquese.
        /// </summary>
        internal static string msg_PleaseIdentifyYourself {
            get {
                return ResourceManager.GetString("msg_PleaseIdentifyYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea imprimir la etiqueta{0}?.
        /// </summary>
        internal static string msg_PrintLabelConfirm {
            get {
                return ResourceManager.GetString("msg_PrintLabelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El guardia ha sido deshabilitado.
        /// </summary>
        internal static string msg_SuccessGuardDisable {
            get {
                return ResourceManager.GetString("msg_SuccessGuardDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El guardia ha sido habilitado.
        /// </summary>
        internal static string msg_SuccessGuardEnable {
            get {
                return ResourceManager.GetString("msg_SuccessGuardEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor carga y/o selecciona una herramienta..
        /// </summary>
        internal static string msg_ToolMandatory {
            get {
                return ResourceManager.GetString("msg_ToolMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe un usuario con esa clave en el sistema.
        /// </summary>
        internal static string msg_UserNotInSystem {
            get {
                return ResourceManager.GetString("msg_UserNotInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de entradas y salidas en caseta.
        /// </summary>
        internal static string title_ExcelReport {
            get {
                return ResourceManager.GetString("title_ExcelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen expandida.
        /// </summary>
        internal static string title_FullScreenImg {
            get {
                return ResourceManager.GetString("title_FullScreenImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardia de seguridad.
        /// </summary>
        internal static string ttl_SecurityGuard {
            get {
                return ResourceManager.GetString("ttl_SecurityGuard", resourceCulture);
            }
        }
    }
}
