//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.User", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        internal static string btn_AddUser {
            get {
                return ResourceManager.GetString("btn_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string btn_ForgotPassword {
            get {
                return ResourceManager.GetString("btn_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string chk_Blocked {
            get {
                return ResourceManager.GetString("chk_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User needs to change password next logon.
        /// </summary>
        internal static string chk_NeedChangePassword {
            get {
                return ResourceManager.GetString("chk_NeedChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete access to this facility ?.
        /// </summary>
        internal static string ConfMSG_UserFacility {
            get {
                return ResourceManager.GetString("ConfMSG_UserFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete access to this storage location ?.
        /// </summary>
        internal static string ConfMSG_UserLocation {
            get {
                return ResourceManager.GetString("ConfMSG_UserLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this access to this warehouse ?.
        /// </summary>
        internal static string ConfMSG_UserWarehouse {
            get {
                return ResourceManager.GetString("ConfMSG_UserWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        internal static string hdr_ChangeYourPassword {
            get {
                return ResourceManager.GetString("hdr_ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        internal static string hdr_LoginYourAccount {
            get {
                return ResourceManager.GetString("hdr_LoginYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user.
        /// </summary>
        internal static string H_CreateUser {
            get {
                return ResourceManager.GetString("H_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string H_EditUser {
            get {
                return ResourceManager.GetString("H_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users management.
        /// </summary>
        internal static string H_Users {
            get {
                return ResourceManager.GetString("H_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base facility.
        /// </summary>
        internal static string lbl_BaseFacility {
            get {
                return ResourceManager.GetString("lbl_BaseFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string lbl_ChangeLanguage {
            get {
                return ResourceManager.GetString("lbl_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string lbl_ChangePassword {
            get {
                return ResourceManager.GetString("lbl_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string lbl_Company {
            get {
                return ResourceManager.GetString("lbl_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string lbl_ConfirmPassword {
            get {
                return ResourceManager.GetString("lbl_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default culture.
        /// </summary>
        internal static string lbl_DefaultCulture {
            get {
                return ResourceManager.GetString("lbl_DefaultCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string lbl_Department {
            get {
                return ResourceManager.GetString("lbl_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or username.
        /// </summary>
        internal static string lbl_EmailorUsername {
            get {
                return ResourceManager.GetString("lbl_EmailorUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee #.
        /// </summary>
        internal static string lbl_EmployeeNumber {
            get {
                return ResourceManager.GetString("lbl_EmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Dashboard.
        /// </summary>
        internal static string lbl_EventsDashboard {
            get {
                return ResourceManager.GetString("lbl_EventsDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string lbl_ExcelFilename {
            get {
                return ResourceManager.GetString("lbl_ExcelFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string lbl_Excelsheetname {
            get {
                return ResourceManager.GetString("lbl_Excelsheetname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string lbl_FirstName {
            get {
                return ResourceManager.GetString("lbl_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full access.
        /// </summary>
        internal static string lbl_FullAccess {
            get {
                return ResourceManager.GetString("lbl_FullAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbl_FullName {
            get {
                return ResourceManager.GetString("lbl_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string lbl_IsDefault {
            get {
                return ResourceManager.GetString("lbl_IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string lbl_LastName {
            get {
                return ResourceManager.GetString("lbl_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string lbl_Line {
            get {
                return ResourceManager.GetString("lbl_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string lbl_Lines {
            get {
                return ResourceManager.GetString("lbl_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lbl_Login {
            get {
                return ResourceManager.GetString("lbl_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string lbl_logout {
            get {
                return ResourceManager.GetString("lbl_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events found.
        /// </summary>
        internal static string lbl_NoEvents {
            get {
                return ResourceManager.GetString("lbl_NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string lbl_OldPassword {
            get {
                return ResourceManager.GetString("lbl_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string lbl_Organization {
            get {
                return ResourceManager.GetString("lbl_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lbl_Password {
            get {
                return ResourceManager.GetString("lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password exp. date.
        /// </summary>
        internal static string lbl_PasswordExpirationDate {
            get {
                return ResourceManager.GetString("lbl_PasswordExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string lbl_Profile {
            get {
                return ResourceManager.GetString("lbl_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles catalog.
        /// </summary>
        internal static string lbl_ProfilesCallout {
            get {
                return ResourceManager.GetString("lbl_ProfilesCallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read only.
        /// </summary>
        internal static string lbl_ReadOnly {
            get {
                return ResourceManager.GetString("lbl_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string lbl_RememberMe {
            get {
                return ResourceManager.GetString("lbl_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember your password?.
        /// </summary>
        internal static string lbl_RememberPassword {
            get {
                return ResourceManager.GetString("lbl_RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore password.
        /// </summary>
        internal static string lbl_RestorePassword {
            get {
                return ResourceManager.GetString("lbl_RestorePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select events.
        /// </summary>
        internal static string lbl_SelectEvents {
            get {
                return ResourceManager.GetString("lbl_SelectEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send password.
        /// </summary>
        internal static string lbl_SendPassword {
            get {
                return ResourceManager.GetString("lbl_SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string lbl_Shift {
            get {
                return ResourceManager.GetString("lbl_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Location.
        /// </summary>
        internal static string lbl_StorageLocation {
            get {
                return ResourceManager.GetString("lbl_StorageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email as user account ID.
        /// </summary>
        internal static string lbl_UseEmailAsUserID {
            get {
                return ResourceManager.GetString("lbl_UseEmailAsUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account ID.
        /// </summary>
        internal static string lbl_UserAccountID {
            get {
                return ResourceManager.GetString("lbl_UserAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string lbl_Username {
            get {
                return ResourceManager.GetString("lbl_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        internal static string lbl_Warehouse {
            get {
                return ResourceManager.GetString("lbl_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That record already exists.
        /// </summary>
        internal static string msg_DuplicateFacility {
            get {
                return ResourceManager.GetString("msg_DuplicateFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password does not match with confirmation password.
        /// </summary>
        internal static string Msg_NotMatch {
            get {
                return ResourceManager.GetString("Msg_NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been added successfully..
        /// </summary>
        internal static string msg_UserCreatedSuccess {
            get {
                return ResourceManager.GetString("msg_UserCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is disabled..
        /// </summary>
        internal static string ntf_UserDisabled {
            get {
                return ResourceManager.GetString("ntf_UserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match, please verify.
        /// </summary>
        internal static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        internal static string PH_FacilityAccess {
            get {
                return ResourceManager.GetString("PH_FacilityAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        internal static string PH_GeneralInformation {
            get {
                return ResourceManager.GetString("PH_GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string PH_Lines {
            get {
                return ResourceManager.GetString("PH_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Locations.
        /// </summary>
        internal static string PH_StorageLocationAccess {
            get {
                return ResourceManager.GetString("PH_StorageLocationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        internal static string PH_WarehouseAccess {
            get {
                return ResourceManager.GetString("PH_WarehouseAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User access.
        /// </summary>
        internal static string TabH_Access {
            get {
                return ResourceManager.GetString("TabH_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        internal static string TabH_GeneralInformation {
            get {
                return ResourceManager.GetString("TabH_GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this line for this user?.
        /// </summary>
        internal static string title_ConfirmDeleteLine {
            get {
                return ResourceManager.GetString("title_ConfirmDeleteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to disable this user ?.
        /// </summary>
        internal static string title_ConfirmDisableUser {
            get {
                return ResourceManager.GetString("title_ConfirmDisableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this profile ?, the information can NOT be recovered.
        /// </summary>
        internal static string title_ConfirmProfileDelete {
            get {
                return ResourceManager.GetString("title_ConfirmProfileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to CEM.
        /// </summary>
        internal static string title_LoginTo {
            get {
                return ResourceManager.GetString("title_LoginTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        internal static string tt_AddNewUser {
            get {
                return ResourceManager.GetString("tt_AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to log in as other user.
        /// </summary>
        internal static string tt_ChangeUser {
            get {
                return ResourceManager.GetString("tt_ChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the new password.
        /// </summary>
        internal static string tt_EnterConfirmPassword {
            get {
                return ResourceManager.GetString("tt_EnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new password.
        /// </summary>
        internal static string tt_EnterNewPassword {
            get {
                return ResourceManager.GetString("tt_EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the old password.
        /// </summary>
        internal static string tt_EnterOldPassword {
            get {
                return ResourceManager.GetString("tt_EnterOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        internal static string tt_EnterPassword {
            get {
                return ResourceManager.GetString("tt_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the username.
        /// </summary>
        internal static string tt_EnterUsername {
            get {
                return ResourceManager.GetString("tt_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search user...
        /// </summary>
        internal static string tt_SearchUser {
            get {
                return ResourceManager.GetString("tt_SearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the email or username used for registration.
        /// </summary>
        internal static string tt_TypeEmail {
            get {
                return ResourceManager.GetString("tt_TypeEmail", resourceCulture);
            }
        }
    }
}
